<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="Francisco Piccolo ">
<meta name="description" content="Overview This book is part of a project made by Cambrige University called Cambridge Series in Statistics and Probabilistic Mathematics aiming to spread knowledge in statistics. As well as this book, there’re other 19 that explore other areas of statistics.
The content of this book is more generic, where the authors explain a range of concepts, from exploratory data analysis, statistical tests, tree models and survival analysis. The book was published in 2006 (the second edition) and I think because of that the authors didn’t use libraries like ggplot or the tidyverse universe." />
<meta name="keywords" content="" />
<meta name="robots" content="noodp" />
<meta name="theme-color" content="#252627" />
<link rel="canonical" href="/posts/2020/05/book-review-data-analysis-and-graphs-with-r-by-j.maindonald-and-j.braun/" />


    <title>
        
            Book Review: Data Analysis and Graphs with R by J.Maindonald and J.Braun :: Glass Frog  — Francisco Piccolo
        
    </title>



<link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/css/flag-icon.min.css" rel="stylesheet"
    type="text/css">



<link rel="stylesheet" href="/main.min.753fac8f03736f0edc9be411eb20cee875dd7bb8e73c8155fbf6a629c863f4ca.css">




    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#252627">
    <link rel="shortcut icon" href="/favicon.ico">
    <meta name="msapplication-TileColor" content="#252627">
    <meta name="theme-color" content="#252627">



<meta itemprop="name" content="Book Review: Data Analysis and Graphs with R by J.Maindonald and J.Braun">
<meta itemprop="description" content="Overview This book is part of a project made by Cambrige University called Cambridge Series in Statistics and Probabilistic Mathematics aiming to spread knowledge in statistics. As well as this book, there’re other 19 that explore other areas of statistics.
The content of this book is more generic, where the authors explain a range of concepts, from exploratory data analysis, statistical tests, tree models and survival analysis. The book was published in 2006 (the second edition) and I think because of that the authors didn’t use libraries like ggplot or the tidyverse universe.">
<meta itemprop="datePublished" content="2020-05-14T00:00:00+00:00" />
<meta itemprop="dateModified" content="2020-05-14T00:00:00+00:00" />
<meta itemprop="wordCount" content="5991">
<meta itemprop="image" content="/"/>



<meta itemprop="keywords" content="" />

<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="/"/>

<meta name="twitter:title" content="Book Review: Data Analysis and Graphs with R by J.Maindonald and J.Braun"/>
<meta name="twitter:description" content="Overview This book is part of a project made by Cambrige University called Cambridge Series in Statistics and Probabilistic Mathematics aiming to spread knowledge in statistics. As well as this book, there’re other 19 that explore other areas of statistics.
The content of this book is more generic, where the authors explain a range of concepts, from exploratory data analysis, statistical tests, tree models and survival analysis. The book was published in 2006 (the second edition) and I think because of that the authors didn’t use libraries like ggplot or the tidyverse universe."/>







    <meta property="article:published_time" content="2020-05-14 00:00:00 &#43;0000 UTC" />








    </head>

    <body class="dark-theme">
        <div class="container">
            <header class="header">
    <span class="header__inner">
        <a href="/" style="text-decoration: none;">
    <div class="logo">
        
            <span class="logo__mark">></span>
            <span class="logo__text">Francisco Piccolo</span>
            <span class="logo__cursor" style=
                  "
                   
                   ">
            </span>
        
    </div>
</a>


        <span class="header__right">
            
                <nav class="menu">
    <ul class="menu__inner"><li><a href="/about/">About</a></li><li><a href="/posts/">Posts</a></li>
    </ul>
</nav>

                <span class="menu-trigger">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path d="M0 0h24v24H0z" fill="none"/>
                        <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/>
                    </svg>
                </span>
            

            <span class="theme-toggle unselectable"><svg class="theme-toggler" width="24" height="24" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M22 41C32.4934 41 41 32.4934 41 22C41 11.5066 32.4934 3 22
  3C11.5066 3 3 11.5066 3 22C3 32.4934 11.5066 41 22 41ZM7 22C7
  13.7157 13.7157 7 22 7V37C13.7157 37 7 30.2843 7 22Z"/>
</svg>
</span>
        </span>
    </span>
</header>


            <div class="content">
                
    <main class="post">

        <div class="post-info">
            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>29 minutes

            

            </p>
        </div>

        <article>
            <h1 class="post-title">
                <a href="/posts/2020/05/book-review-data-analysis-and-graphs-with-r-by-j.maindonald-and-j.braun/">Book Review: Data Analysis and Graphs with R by J.Maindonald and J.Braun</a>
            </h1>

            

            <div class="post-content">
                


<div id="overview" class="section level2">
<h2><strong>Overview</strong></h2>
<p>This book is part of a project made by Cambrige University called <strong>Cambridge Series in Statistics and Probabilistic Mathematics</strong> aiming to spread knowledge in statistics. As well as this book, there’re other 19 that explore other areas of statistics.</p>
<p>The content of this book is more generic, where the authors explain a range of concepts, from exploratory data analysis, statistical tests, tree models and survival analysis. The book was published in 2006 (the second edition) and I think because of that the authors didn’t use libraries like ggplot or the tidyverse universe.</p>
<p>The explanations given by the authors are clear and easy to understand, also the utilization of data sets from R packages (e.g. DAAG) simplify reproducibility of examples and execution of models to solve the proposed exercises.</p>
<div class="figure">
<img src="/images/2020-02-07_data_analysis_with_r.png" alt="Book cover" />
<p class="caption">Book cover</p>
</div>
</div>
<div id="chapter-1---a-brief-introduction-to-r" class="section level2">
<h2><strong>Chapter 1 - A brief introduction to R</strong></h2>
<p>In this chapter the focus is to introduce the R enviroment to the reader. With this goal, the authors explain the types of data that R can handle, how to build functions and what kind of graphs are possible with this tool. Let’s see some exercises presented this chapter.</p>
<div id="exercises" class="section level3">
<h3><strong>Exercises</strong></h3>
</div>
<div id="the-following-table-gives-the-size-of-the-floor-area-ha-and-the-price-a000-for-15-houses-sold-in-the-canberra-australia-suburb-of-aranda-in-1999." class="section level3">
<h3><strong>1. The following table gives the size of the floor area (ha) and the price ($A000), for 15 houses sold in the Canberra (Australia) suburb of Aranda in 1999.</strong></h3>
<pre class="r"><code>df &lt;- data.frame(area = c(694,905,802,1366,716,963,821,714,1018,887,790,696,771,1006,1191),
                 sale.price = c(192,215,215,274,112.7,185,212,220,276,260,221,255,260,293,375))</code></pre>
</div>
<div id="a-plot-sale.price-versus-area." class="section level3">
<h3><strong>a) Plot sale.price versus area.</strong></h3>
<p><strong>A:</strong> For this, I’ll use ggplot library instead of base R plots, because it’s easier and prettier.</p>
<pre class="r"><code>df %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = area, y = sale.price), 
             color = &quot;darkred&quot;)+
  theme_graph()+
  labs(title = &quot;Sales Price vs Area&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="b-use-hist-command-to-plot-a-histogram-of-the-sales.price." class="section level3">
<h3><strong>b) Use hist() command to plot a histogram of the sales.price.</strong></h3>
<p><strong>A:</strong> In this alternative I won’t use the hist() command. Instead I’ll opt for the geom_histogram from ggplot.</p>
<pre class="r"><code>df %&gt;% 
  ggplot2::ggplot()+
  geom_histogram(mapping = aes(x = sale.price),
                 fill = &quot;darkblue&quot;,
                 alpha = .4)+
  theme_graph()+
  labs(title = &quot;Sales Price Histogram&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="c-repeat-a-and-b-after-taking-logarithms-of-sale-prices." class="section level3">
<h3><strong>c) Repeat (a) and (b) after taking logarithms of sale prices.</strong></h3>
<p><strong>A:</strong> It’s possible to reproduce the same graphs and put the log() formula on the variables inside aes() function.</p>
<pre class="r"><code>df %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = log(area), y = log(sale.price)),
             color = &quot;darkred&quot;)+
  theme_graph()+
  labs(title = &quot;Sales Price vs Area using log transformation&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The histogram will follow the same logic.</p>
<pre class="r"><code>df %&gt;% 
  ggplot2::ggplot()+
  geom_histogram(mapping = aes(x = log(sale.price)),
                 fill = &quot;darkblue&quot;,
                 alpha = .4)+
  theme_graph()+
  labs(title = &quot;Sale Price Histograma&quot;,
       subtitle = &quot;Log transformed&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
</div>
<div id="chapter-2---styles-of-data-analysis" class="section level2">
<h2><strong>Chapter 2 - Styles of data analysis</strong></h2>
<p>This chapter explains about exploratory data analysis, a technique developed by John Tukey to support researchers during their initial problem exploration. The aythors present the types of graphs available for researchers and when to use each of them. Also, they explain about outliers and data skewness, showing how to deal with each situation.</p>
<div id="exercises-1" class="section level3">
<h3><strong>Exercises</strong></h3>
</div>
<div id="use-the-lattice-function-bwplot-to-display-for-each-combination-of-site-and-sex-in-the-data-frame-possumdaag-package-the-distribution-of-ages.-show-the-different-sites-on-the-same-panel-with-different-panels-for-different-sexes." class="section level3">
<h3><strong>1) Use the lattice function bwplot() to display, for each combination of <em>site</em> and <em>sex</em> in the data frame <em>possum</em>(DAAG package), the distribution of ages. Show the different sites on the same panel, with different panels for different sexes.</strong></h3>
<p><strong>A:</strong> bwplot means box and whisker plot (a.k.a boxplot). It’s a good visualization to present distribution among different categories. Let’s create the boxplot using ggplot.</p>
<pre class="r"><code>DAAG::possum %&gt;%
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = age, group = site, fill = as.factor(site)),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  theme_graph()+
  theme(legend.title = element_text(size = 7))+
  scale_fill_viridis_d()+
  facet_grid(~sex)+
  labs(title = &quot;Age distribution for different sites&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="plot-a-histogram-of-the-earconch-measurements-for-the-possum-data.-the-distribution-should-appear-bimodal-two-peaks.-this-is-a-simple-indication-of-clustering-possibly-due-to-sex-differences.-obtain-side-by-side-boxplots-of-the-male-and-female-earconch-measurements.-how-do-these-measurement-distributions-differ-can-you-predict-what-the-corresponding-histograms-would-look-like-plot-them-to-check-your-answer." class="section level3">
<h3><strong>3) Plot a histogram of the earconch measurements for the possum data. The distribution should appear bimodal (two peaks). This is a simple indication of clustering, possibly due to sex differences. Obtain side-by-side boxplots of the male and female earconch measurements. How do these measurement distributions differ? Can you predict what the corresponding histograms would look like? Plot them to check your answer.</strong></h3>
<p><strong>A:</strong> If the data ser contains men and women in a similar proportion, the histogram will be bicaudal, because the measure differ for each gender.</p>
<pre class="r"><code>DAAG::possum %&gt;% 
  ggplot2::ggplot()+
  geom_histogram(mapping = aes(x = earconch),
                 fill = &quot;darkred&quot;,
                 alpha = .2,
                 color = &quot;darkred&quot;,
                 size = 1)+
  theme_graph()+
  labs(title = &quot;Earconch Distribution&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Now let’s see the boxblot for each gender.</p>
<pre class="r"><code>DAAG::possum %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = earconch, fill = sex),
               alpha = .2)+
  scale_fill_viridis_d()+
  theme_graph()+
  labs(title = &quot;Earconch box plot distribution&quot;,
       x = &quot;&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
</div>
<div id="chapter-3---statistical-models" class="section level2">
<h2><strong>Chapter 3 - Statistical models</strong></h2>
<p>This chapter introduce the fundations of statistical models. First the authors explain the importance of statistical models, showing the difference between physical phenomenon and random events that has singnal and noise well established.</p>
<p>They affirm that models have to provide accurate inferences in order to allow predictions. Thus, for researchers build reliable models it’s necessary to set hypothesis about data distribution, sampling method and also assumptions about the parameters of the model.</p>
<p>As the assumption of the data distribution is an important part of model definition, the authors explain how to validate if the data is normally distributed, using visual displays (i.e. histograms on qq-plots) or formal tests.</p>
<div id="exercises-2" class="section level3">
<h3><strong>Exercises</strong></h3>
</div>
<div id="use-y---rnorm100-to-generate-a-random-sample-of-100-numbers-from-a-normal-distribution.-calculate-the-mean-and-standard-deviation-of-y.-now-put-the-calculation-in-a-loop-and-repeat-25-times.-store-the-25-means-in-a-vector-named-av.-calculate-the-standard-deviation-of-the-values-in-av." class="section level3">
<h3><strong>2) Use y &lt;- rnorm(100) to generate a random sample of 100 numbers from a normal distribution. Calculate the mean and standard deviation of y. Now put the calculation in a loop and repeat 25 times. Store the 25 means in a vector named av. Calculate the standard deviation of the values in av.</strong></h3>
<pre class="r"><code>y &lt;- rnorm(100)

tibble(mean = mean(y),
           sd = sd(y))</code></pre>
<pre><code>## # A tibble: 1 x 2
##      mean    sd
##     &lt;dbl&gt; &lt;dbl&gt;
## 1 -0.0223  1.00</code></pre>
<p><strong>A:</strong> In order to run this process, it’s necessary to create an empty variable with 25 slots available, then create a <em>for lopp</em> that will calculate the mean for a sample of 100 values taken from a normal distribution, 25 times.</p>
<pre class="r"><code># Creating an empty variable with 25 slots
output &lt;- rep(NA,25)

# Creating the for loop
for(i in 1:25){
  output[i] &lt;- data.frame(
    mean(rnorm(100))
  )
}

# Extracting the output and inserting it in a data.frame
df &lt;- data.frame(
  a = matrix(unlist(output),nrow = 25,byrow = F), stringsAsFactors = F)

# Calculating the mean and sd
tibble(mean = mean(df[,1]),
           sd = sd(df[,1]))</code></pre>
<pre><code>## # A tibble: 1 x 2
##       mean    sd
##      &lt;dbl&gt; &lt;dbl&gt;
## 1 -0.00457 0.112</code></pre>
</div>
<div id="create-a-function-that-does-the-calculations-of-exercise-2.-run-the-function-several-times-showing-each-of-the-distributions-of-25-means-in-a-density-plot." class="section level3">
<h3><strong>3) Create a function that does the calculations of Exercise 2. Run the function several times, showing each of the distributions of 25 means in a density plot.</strong></h3>
<pre class="r"><code># Creating the function, x = repetitions, y = random samples
fun &lt;- function(x, y){
  output &lt;- rep(NA, x)
  for(i in 1:x){
    output[i] &lt;- data.frame(
      round(mean(rnorm(y)), digits = 2)
    )
  }
  df &lt;- data.frame(
    a = matrix(unlist(output), 
               nrow = x,
               byrow = T), 
    stringsAsFactors = F)
}

# Running the function and ploting the results
fun(25, 100) %&gt;% 
  ggplot2::ggplot()+
  geom_density(mapping = aes(x = a),
               fill = &quot;dark orange&quot;,
               alpha = .2)+
  theme_graph()+
  labs(title = &quot;Density plot for &quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
</div>
<div id="chapter-4---an-introduction-to-formal-inference" class="section level2">
<h2><strong>Chapter 4 - An introduction to formal inference</strong></h2>
<p>This chapter introduces some basic concepts about statistical inference. The main concepts about this subject are <strong>Standard Error of the Mean</strong>; <strong>student distribution</strong>; <strong>degress of freedom</strong>; <strong>p-values</strong>; <strong>confidence intervals</strong>; <strong>test of hypothesis</strong>.</p>
<p>The authors explain the formulas for some of these variables, how to perform hypothesis test and build confidence intervals and also, why researchers are moving from hypothesis test to confidence intervals.</p>
<div id="exercises-3" class="section level3">
<h3><strong>Exercises</strong></h3>
</div>
<div id="in-the-data-set-nsw74demo-daag-determine-95-confidence-intervals-for-a-the-1974-incomes-of-each-of-the-treated-and-control-groups-b-the-1975-incomes-of-each-group-c-the-1978-incomes-of-each-group.-finally-calculate-a-95-confidence-interval-for-the-difference-in-income-between-treated-and-controls-in-1978." class="section level3">
<h3><strong>1) In the data set nsw74demo (DAAG) determine 95% confidence intervals for: (a) the 1974 incomes of each of the “treated” and “control” groups; (b) the 1975 incomes of each group; (c) the 1978 incomes of each group. Finally, calculate a 95% confidence interval for the difference in income between treated and controls in 1978.</strong></h3>
<p><strong>A:</strong> As explained in this chapter, confidence intervals are build using the following equation:</p>
<p><span class="math display">\[\mu - (t_\frac{\alpha}{2} \times SEM)\]</span>
Changing the signals from minus to plus in order to obtain the the upper limit instead of the lower.</p>
<p>Where:</p>
<p><span class="math inline">\(\mu\)</span> = the sample mean given in the data set.</p>
<p>$t_ = $ Critical t value obtained using the confidence level (<span class="math inline">\(\alpha\)</span>) and dividing by two because we’ll validate the two side of the distribution (bicaudal test).</p>
<p><span class="math inline">\(SEM = \frac{s}{\sqrt{n}}\)</span>.</p>
<p>$s = $ Sample standard deviation.</p>
<p>$n = $ Number of observations taken.</p>
<p>In the data set mentioned, we have one group being studied in different time and then being compared with a control group. The groups are identified by the field <strong>trt</strong> that will be equal 1 for treatment groups and 0 for control grups. Let’s develop a data.frame that will allow us to answer all three questions.</p>
<p>First I’ll group the data set and take the average income of each group in different columns. Then, I’ll calculate the critical t value from the student distribution and with this value I’ll create the standard error of the mean for each timeframe. With this values it will be possible to calculate the limits of the invervals.</p>
<pre class="r"><code>DAAG::nsw74demo %&gt;%
  mutate(group = ifelse(trt == 0, &quot;control&quot;,&quot;test&quot;)) %&gt;% 
  group_by(group) %&gt;% 
  summarise(n = n(),
            avg_income_74 = mean(re74),
            avg_income_75 = mean(re75),
            avg_income_78 = mean(re78),
            sem_74 = sd(re74)/sqrt(n),
            sem_75 = sd(re75)/sqrt(n),
            sem_78 = sd(re78)/sqrt(n)) %&gt;% 
  mutate(critical_t = qt(0.975, n),
         sem_74_times_critical_t = sem_74 * critical_t,
         sem_75_times_critical_t = sem_75 * critical_t,
         sem_78_times_critical_t = sem_78 * critical_t,
         inc74_lower = avg_income_74 - sem_74_times_critical_t,
         inc74_upper = avg_income_74 + sem_74_times_critical_t,
         inc75_lower = avg_income_75 - sem_74_times_critical_t,
         inc75_upper = avg_income_75 + sem_74_times_critical_t,
         inc78_lower = avg_income_78 - sem_74_times_critical_t,
         inc78_upper = avg_income_78 + sem_74_times_critical_t)</code></pre>
<pre><code>## # A tibble: 2 x 18
##   group     n avg_income_74 avg_income_75 avg_income_78 sem_74 sem_75 sem_78
##   &lt;chr&gt; &lt;int&gt;         &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 cont~   260         2107.         1267.         4555.   353.   192.   340.
## 2 test    185         2096.         1532.         6349.   359.   237.   578.
## # ... with 10 more variables: critical_t &lt;dbl&gt;, sem_74_times_critical_t &lt;dbl&gt;,
## #   sem_75_times_critical_t &lt;dbl&gt;, sem_78_times_critical_t &lt;dbl&gt;,
## #   inc74_lower &lt;dbl&gt;, inc74_upper &lt;dbl&gt;, inc75_lower &lt;dbl&gt;, inc75_upper &lt;dbl&gt;,
## #   inc78_lower &lt;dbl&gt;, inc78_upper &lt;dbl&gt;</code></pre>
<p>Now, the final question demand us to estimate the income difference between treated and control groups in 1978, with 95% of confidence. For this estimation, the book recommends the following equation:</p>
<p><span class="math inline">\(SED = \sqrt{SEM_1^2 + SEM_2^2}\)</span></p>
<p>Where:</p>
<p>SED = <em>standard error of the difference</em></p>
<p><span class="math inline">\(SEM_control\)</span> = <em>standard error of the mean</em></p>
<p><span class="math inline">\(SEM_test\)</span> = <em>standard error of the mean</em></p>
<p><span class="math inline">\(SED = \sqrt{415^2+680^2}\)</span></p>
<p><span class="math inline">\(SED = \sqrt{172.225+462.400}\)</span></p>
<p><span class="math inline">\(SED = 796,6\)</span></p>
<p><strong>A:</strong> The income difference between groups, with 95% of confidence is of 796,6.</p>
</div>
<div id="draw-graphs-that-show-for-degrees-of-freedom-between-1-and-100-the-change-in-the-5-critical-value-of-the-t-statistic.-compare-a-graph-on-which-neither-axis-is-transformed-with-a-graph-on-which-the-respective-axis-scales-are-proportional-to-logt-statistic-and-logdegrees-of-freedom.-which-graph-gives-the-more-useful-visual-indication-of-the-change-in-the-5-critical-value-of-the-t-statistic-with-increasing-degrees-of-freedom." class="section level3">
<h3><strong>2) Draw graphs that show, for degrees of freedom between 1 and 100, the change in the 5% critical value of the t-statistic. Compare a graph on which neither axis is transformed with a graph on which the respective axis scales are proportional to log(t-statistic) and log(degrees of freedom). Which graph gives the more useful visual indication of the change in the 5% critical value of the t-statistic with increasing degrees of freedom?.</strong></h3>
<pre class="r"><code>t_value &lt;- 
  data.frame(df = seq(1, 100, by = 1)) %&gt;% 
  mutate(t_value = qt(0.975, df = row_number()))

g1 &lt;- t_value %&gt;% 
  ggplot2::ggplot()+
  geom_line(mapping = aes(x = df, y = t_value))+
  scale_x_log10()+
  scale_y_log10()+
  theme_graph()+
  labs(title = &quot;Log transformation applied&quot;,
       x = &quot;log_10 of Degrees of freedom&quot;,
       y = &quot;log_10 of t-statistics&quot;)

g2 &lt;- t_value %&gt;% 
  ggplot2::ggplot()+
  geom_line(mapping = aes(x = df, y = t_value))+
  theme_graph()+
  labs(title = &quot;Log transformation not applied&quot;,
       x = &quot;Degrees of freedom&quot;,
       y = &quot;t-statistics&quot;)

g1 + g2</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="generate-a-random-sample-of-10-numbers-from-a-normal-distribution-with-mean-0-and-standard-deviation-2.-use-t.test-to-test-the-null-hypothesis-that-the-mean-is-0.-now-generate-a-random-sample-of-10-numbers-from-a-normal-distribution-with-mean-1.5-and-standard-deviation-2.-again-use-t.test-to-test-the-null-hypothesis-that-the-mean-is-0.-finally-write-a-function-that-generates-a-random-sample-of-n-numbers-from-a-normal-distribution-with-mean-and-standard-deviation-1-and-returns-the-p-value-for-the-test-that-the-mean-is-0.." class="section level3">
<h3><strong>3) Generate a random sample of 10 numbers from a normal distribution with mean 0 and standard deviation 2. Use t.test() to test the null hypothesis that the mean is 0. Now generate a random sample of 10 numbers from a normal distribution with mean 1.5 and standard deviation 2. Again use t.test() to test the null hypothesis that the mean is 0. Finally write a function that generates a random sample of n numbers from a normal distribution with mean and standard deviation 1, and returns the p-value for the test that the mean is 0..</strong></h3>
<p><strong>A:</strong> This question demands us to make a hypothesis test using a random data set. Let’s create this data set with using a normal distribution.</p>
<pre class="r"><code>df &lt;- rnorm(n = 10, mean = 0, sd = 2)

# Visualizing the data set
df</code></pre>
<pre><code>##  [1]  0.3384814 -2.0430390  1.2326679  2.3316873 -1.1990960 -0.1691513
##  [7] -1.0768319  3.2526479 -0.6622174  0.9717683</code></pre>
<p>Now, let’s make R calculate the t.test() and see the result and after this I’ll calculate the p-value by hand to reach the same result. I expect that the null hypothesis (<span class="math inline">\(H0: \mu = 0\)</span>) won’t be rejected, because the data set was generated from a population with mean 0.</p>
<pre class="r"><code>df %&gt;% 
  t.test(mu = 0, conf.level = 0.975)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  .
## t = 0.56543, df = 9, p-value = 0.5856
## alternative hypothesis: true mean is not equal to 0
## 97.5 percent confidence interval:
##  -1.115938  1.711322
## sample estimates:
## mean of x 
## 0.2976917</code></pre>
<p>The t.test from R generated a p-value of 0.7261. In this case we can’t reject H0 as expected. Now let’s make the calculation step by step.</p>
<pre class="r"><code>mean &lt;- mean(df)
sd &lt;- sd(df)
n_sqrt &lt;- sqrt(length(df))

sem &lt;- sd/n_sqrt

(1-pt(mean/sem, 10-1))*2</code></pre>
<pre><code>## [1] 0.5856006</code></pre>
<p>The same p-value was obtained. Thus, we can rely on our t.test() from R and understand what it is happening on backstage.</p>
<p>Now, the question ask us to perform the same method in a population with mean 1.5. In this case, let’s make the sample generation and statistical modeling all at once.</p>
<pre class="r"><code>data.frame(rnorm(n = 10, mean = 1.5, sd = 2)) %&gt;% 
  t.test(mu = 0, conf.level = 0.975)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  .
## t = 2.0968, df = 9, p-value = 0.06546
## alternative hypothesis: true mean is not equal to 0
## 97.5 percent confidence interval:
##  -0.3985366  3.2399249
## sample estimates:
## mean of x 
##  1.420694</code></pre>
<p>In this test, the p-value obtained was lower, but not sufficient to make us reject H0: <span class="math inline">\(\mu = 0\)</span>. Maybe it’s because the sample size is small. Let’s remake the test with a larger sample.</p>
<pre class="r"><code>data.frame(rnorm(n = 100, mean = 1.5, sd = 2)) %&gt;% 
  t.test(mu = 0, conf.level = 0.975)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  .
## t = 7.9088, df = 99, p-value = 3.762e-12
## alternative hypothesis: true mean is not equal to 0
## 97.5 percent confidence interval:
##  1.083773 1.959600
## sample estimates:
## mean of x 
##  1.521686</code></pre>
<p>Now, the p-value is pretty lower and we can reject H0 with a 95% of confidence.</p>
</div>
<div id="use-the-function-that-was-created-in-exercise-3-to-generate-50-independent-p-values-all-with-a-sample-size-n-10-and-with-mean-0.-use-qqplot-with-the-parameter-setting-x-qunifppoints50-to-compare-the-distribution-of-the-p-values-with-that-of-a-uniform-random-variable-on-the-interval-0-1.-comment-on-the-plot." class="section level3">
<h3><strong>4) Use the function that was created in Exercise 3 to generate 50 independent p-values, all with a sample size n = 10 and with mean = 0. Use qqplot(), with the parameter setting x = qunif(ppoints(50)), to compare the distribution of the p-values with that of a uniform random variable, on the interval [0, 1]. Comment on the plot.</strong></h3>
<p><strong>A:</strong> In the last exercise I didn’t create the function, then I’ll create it now. The function will generates a random sample of <em>n</em> numbers from a normal distribution with mean <span class="math inline">\(\mu = 0\)</span> and standard deviation 1, and will return the <strong>p-value</strong> from a test considering <strong>H0: <span class="math inline">\(\mu = 0\)</span></strong>.</p>
<p>The first thing we have to make in order to build a function, is to create an empty vector that will receive the output. Then, we create the function and fill this vector with the output from the function. Let’s see how it works.</p>
<pre class="r"><code># Creating the empty vector
output &lt;- rep(NA,50)

# Creating the function with the p-value
for(i in 1:50){
  sample &lt;- rnorm(n = 10, mean = 0, sd = 1)
  mean &lt;- mean(sample)
  sd &lt;- sd(sample)
  sem &lt;- sd/sqrt(10)
  output[i] &lt;- data.frame(p_value = (1-pt((abs(mean)/sem),9))*2)
}

# Putting function output in a data.frame
df &lt;- data.frame(a = matrix(unlist(output), 
                            nrow = 50, 
                            byrow = T))</code></pre>
<p>Now we have the data.frame and we’re ready to plot the requested qq-plot. This plot is nice to visualize how normal is the data distribution. For this case, we have a sample obtained from a population with mean 0 and sd 1 and we’re testing the Null Hypothesis that population mean is 0. Then, the p-value has to by high (more than 0.05 at least) in order to preclude the rejection of H0. The qq-plot will show that p-value is normally distributed. I’ll also generate a histogram to show that p-value is high in most of the cases (the data.frame contains 50 p-values). Let’s see both graphs</p>
<pre class="r"><code># Generating the qq-plot
g1 &lt;- df %&gt;% 
  ggplot2::ggplot()+
  geom_qq(mapping = aes(sample = a),
          color = &quot;dark blue&quot;)+
  geom_qq_line(mapping = aes(sample = a),
               lty = 2,
               color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;QQ plot for p-values&quot;)

# Generating the histogram
g2 &lt;- df %&gt;% 
  ggplot2::ggplot()+
  geom_histogram(mapping = aes(x = a),
                 fill = &quot;dark blue&quot;,
                 alpha = .3)+
  geom_vline(xintercept = 0.05,
             lty = 2,
             color = &quot;dark orange&quot;)+
  scale_x_continuous(labels = scales::percent)+
  theme_graph()+
  labs(title = &quot;Histogram of p-values&quot;)

g1+g2</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Look that most of the p-values generated are on the righ side of the histogram’s yellow dached line. This indicates that most of the Null Hypothesis wouldn’t be rejected considering a significance level of 5%.</p>
</div>
<div id="here-we-generate-random-normal-numbers-with-a-sequential-dependence-structure.-repeat-this-several-times.-there-should-be-no-consistent-pattern-in-the-acf-plot-for-different-random-samples-y1.-there-will-be-a-fairly-consistent-pattern-in-the-acf-plot-for-y-a-result-of-the-correlation-that-is-introduced-by-adding-to-each-value-the-next-value-in-the-sequence." class="section level3">
<h3><strong>6) Here we generate random normal numbers with a sequential dependence structure. Repeat this several times. There should be no consistent pattern in the ACF plot for different random samples y1. There will be a fairly consistent pattern in the ACF plot for y, a result of the correlation that is introduced by adding to each value the next value in the sequence.</strong></h3>
<pre class="r"><code># Random numbers mentioned in the exercise
y1 &lt;- rnorm(51)
y &lt;- y1[-1] + y1[-51]
acf(y1) # acf is ‘autocorrelation function’</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>acf(y)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
</div>
<div id="a-for-each-column-of-the-data-set-nsw74psid1-after-the-first-compare-the-control-group-trt0-with-the-treatment-group-trt1.-use-overlaid-density-plots-to-compare-the-continuous-variables-and-two-way-tables-to-compare-the-binary-01-variables.-where-are-the-greatest-differences." class="section level3">
<h3><strong>8) (a) For each column of the data set nsw74psid1 after the first, compare the control group (trt==0) with the treatment group (trt==1). Use overlaid density plots to compare the continuous variables, and two-way tables to compare the binary (0/1) variables. Where are the greatest differences?.</strong></h3>
<p><strong>A:</strong> In this exercise I’ll generate box plots for continuous variables in order to compare the control and treated groups.</p>
<pre class="r"><code>g1 &lt;- DAAG::nsw74psid1 %&gt;%
  mutate(trt = as.factor(trt)) %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = age, group = trt, color = trt),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  scale_color_brewer(type = &quot;qual&quot;)+
  theme(axis.text.x = element_blank())+
  theme_graph()

g2 &lt;- DAAG::nsw74psid1 %&gt;% 
  mutate(trt = as.factor(trt)) %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = educ, group = trt, color = trt),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  scale_color_brewer(type = &quot;qual&quot;)+
  theme_graph()+
  theme(axis.text.x = element_blank())

g3 &lt;- DAAG::nsw74psid1 %&gt;% 
  mutate(trt = as.factor(trt)) %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = re74, group = trt, color = trt),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  scale_y_log10(labels = scales::comma)+
  scale_color_brewer(type = &quot;qual&quot;)+
  theme_graph()+
  theme(axis.text.x = element_blank())

g4 &lt;- DAAG::nsw74psid1 %&gt;% 
  mutate(trt = as.factor(trt)) %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = re75, group = trt, color = trt),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  scale_y_log10(labels = scales::comma)+
  scale_color_brewer(type = &quot;qual&quot;)+
  theme_graph()+
  theme(axis.text.x = element_blank())

g5 &lt;- DAAG::nsw74psid1 %&gt;% 
  mutate(trt = as.factor(trt)) %&gt;% 
  ggplot2::ggplot()+
  geom_boxplot(mapping = aes(y = re78, group = trt, color = trt),
               outlier.shape = 20,
               outlier.color = &quot;black&quot;)+
  scale_y_log10(labels = scales::comma)+
  scale_color_brewer(type = &quot;qual&quot;)+
  theme_graph()+
  theme(axis.text.x = element_blank())

# Putting all graphs together
plots &lt;- (g1+g2)/(g3|g4|g5)

plots +
  plot_layout(guides = &quot;collect&quot;)+
  plot_annotation(title = &quot;Continuous variables comparison&quot;,
                  subtitle = &quot;Control (0) and treated (1) groups&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
</div>
<div id="chapter-5---regression-with-a-single-predictor" class="section level2">
<h2><strong>Chapter 5 - Regression with a Single Predictor</strong></h2>
<p>This chapter provides some foundations on linear regression models, where the authors walk through parameters estimation using confidence intervals and hypothesis test, R’s <strong>lm function</strong> and outputs, residual analysis and the use of cross-validation and bootstrap to reproduce the model multiple times in order to assess how it’s stable and reliable.</p>
<div id="for-each-of-the-data-sets-elastic1-and-elastic2-determine-the-regression-of-stretch-on-distance.-in-each-case-determine." class="section level3">
<h3><strong>2) For each of the data sets <em>elastic1</em> and <em>elastic2</em>, determine the regression of stretch on distance. In each case determine.</strong></h3>
<p><strong>(i) fitted values and standard errors of fitted values</strong></p>
<p><strong>(ii) the R² statistic. Compare the two sets of results. What is the key difference between the two sets of data?</strong></p>
<p><strong>Use the robust regression function rlm() from the MASS package to fit lines to the data in elastic1 and elastic2. Compare the results with those from use of lm(). Compare regression coefficients, standard errors of coefficients, and plots of residuals against fitted values.</strong></p>
<p><strong>A:</strong> The data sets mentioned for this exercise is:</p>
<pre class="r"><code>df1 &lt;- data.frame(stretch = c(46,54,48,50,44,42,52),
                  distance = c(183,217,189,208,178,150,249))

df2 &lt;- data.frame(stretch = c(25,45,35,40,55,50,30,50,60),
                  distance = c(71,196,127,187,249,217,114,228,291))</code></pre>
<p>With these two data sets, let’s determine the regression of stretch (y) on distance (x). For this analysis, I’ll plot the scaterplot with the model output as anottation on the graph.</p>
<pre class="r"><code>g1 &lt;- df1 %&gt;%
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = distance, y = stretch),
             shape = 20)+
  geom_smooth(mapping = aes(x = distance, y = stretch),
              method = &quot;lm&quot;,
              formula = &quot;y ~ x&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  geom_text(mapping = aes(x = 165, y = 55, label = &quot;y = 24.13 + 0.12 X1&quot;),
            size = 3)+
  geom_text(mapping = aes(x = 167, y = 54, label = &quot;Std.Error = (5.41) | (0.027)&quot;),
            size = 3)+
  geom_text(mapping = aes(x = 165, y = 53, label = &quot;R²: 79.92%&quot;),
            size = 3)+
  theme_graph()

g2 &lt;- df2 %&gt;%
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = distance, y = stretch),
             shape = 20)+
  geom_smooth(mapping = aes(x = distance, y = stretch),
              method = &quot;lm&quot;,
              formula = &quot;y ~ x&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  geom_text(mapping = aes(x = 105, y = 60, label = &quot;y = 12.56 + 0.16 X1&quot;),
            size = 3)+
  geom_text(mapping = aes(x = 105, y = 55, label = &quot;Std.Error = (1.73) | (0.009)&quot;),
            size = 3)+
  geom_text(mapping = aes(x = 105, y = 50, label = &quot;R²: 98.08%&quot;),
            size = 3)+
  theme_graph()

g1/g2</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The second data set has a stronger correlation betweem stretch and distance than the first one. The estimators of the second model also are more reliable given their lower standard error.</p>
<p>Now let’s see what we obtain using the function <em>rlm()</em> from the <em>MASS</em> package.</p>
<pre class="r"><code>df1 %&gt;% 
  MASS::rlm(stretch ~ distance, data = .) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call: rlm(formula = stretch ~ distance, data = .)
## Residuals:
##       1       2       3       4       5       6       7 
## -0.2207  3.8393  1.0840  0.8822 -1.6413 -0.3967 -1.8689 
## 
## Coefficients:
##             Value   Std. Error t value
## (Intercept) 25.0146  5.0698     4.9341
## distance     0.1159  0.0255     4.5366
## 
## Residual standard error: 1.607 on 5 degrees of freedom</code></pre>
<pre class="r"><code>df2 %&gt;% 
  MASS::rlm(stretch ~ distance, data = .) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call: rlm(formula = stretch ~ distance, data = .)
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -3.49045 -0.63426  0.02595  1.28920  1.56422 
## 
## Coefficients:
##             Value   Std. Error t value
## (Intercept) 12.6646  1.7257     7.3390
## distance     0.1648  0.0087    18.9266
## 
## Residual standard error: 1.911 on 7 degrees of freedom</code></pre>
</div>
<div id="using-the-data-frame-cars-datasets-plot-distance-i.e.-stopping-distance-versus-speed.-fit-a-line-to-this-relationship-and-plot-the-line.-then-try-fitting-and-plotting-a-quadratic-curve.-does-the-quadratic-curve-give-a-useful-improvement-to-the-fit" class="section level3">
<h3><strong>3) Using the data frame cars (datasets), plot distance (i.e. stopping distance) versus speed. Fit a line to this relationship, and plot the line. Then try fitting and plotting a quadratic curve. Does the quadratic curve give a useful improvement to the fit?</strong></h3>
<p><strong>A:</strong> Let’s plot the scateplot and both curves (linear and quadratic curves). I’ll consider distance on the y axis and speed on the x axis, in order to evaluate what distance will take for the car to stop given it’s speed before it start to brake.</p>
<pre class="r"><code>cars %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = speed, y = dist),
             shape = 7,
             color = &quot;dark blue&quot;)+
  geom_smooth(mapping = aes(x = speed, y = dist),
              method = &quot;lm&quot;,
              formula = &quot;y ~ x&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  geom_smooth(mapping = aes(x = speed, y = dist),
              method = &quot;lm&quot;,
              formula = &quot;y ~ I(x^1.7)&quot;,
              se = F,
              lty = 2,
              color = &quot;dark red&quot;)</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Know, let’s summarise both regression models and compare them. The comparison will consider the residual standard error.</p>
<pre class="r"><code>cars %&gt;% 
  lm(formula = &quot;dist ~ speed&quot;) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = &quot;dist ~ speed&quot;, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.069  -9.525  -2.272   9.215  43.201 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -17.5791     6.7584  -2.601   0.0123 *  
## speed         3.9324     0.4155   9.464 1.49e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.38 on 48 degrees of freedom
## Multiple R-squared:  0.6511, Adjusted R-squared:  0.6438 
## F-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12</code></pre>
<pre class="r"><code>cars %&gt;% 
  lm(formula = &quot;dist ~ I(speed^1.7)&quot;) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = &quot;dist ~ I(speed^1.7)&quot;, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.875  -9.330  -3.155   4.548  45.036 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.88615    4.52194   0.859    0.394    
## I(speed^1.7)  0.34997    0.03573   9.796 4.96e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.03 on 48 degrees of freedom
## Multiple R-squared:  0.6666, Adjusted R-squared:  0.6596 
## F-statistic: 95.96 on 1 and 48 DF,  p-value: 4.956e-13</code></pre>
<p>Thus, we have the second model with a residual standard error of 15.03, lower than the 15.38 given by the first model (linear). Then, apparently the second model is better.</p>
</div>
<div id="calculate-volumes-volume-and-page-areas-area-for-the-books-on-which-information-is-given-in-the-data-frame-oddbooks-daag." class="section level3">
<h3><strong>4) Calculate volumes (volume) and page areas (area) for the books on which information is given in the data frame oddbooks (DAAG).</strong></h3>
</div>
<div id="a-plot-logweight-against-logvolume-and-fit-a-regression-line." class="section level3">
<h3><strong>a) Plot log(weight) against log(volume), and fit a regression line.</strong></h3>
<pre class="r"><code>DAAG::oddbooks %&gt;% 
  mutate(volume = (height*breadth*weight)) %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = log(weight), y = log(volume)))+
  geom_smooth(mapping = aes(x = log(weight), y = log(volume)),
              method = &quot;lm&quot;,
              formula = &quot;y ~ x&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Volume vs Weigth scaterplot&quot;)</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
</div>
<div id="b-plot-logweight-against-logarea-and-again-fit-a-regression-line." class="section level3">
<h3><strong>b) Plot log(weight) against log(area), and again fit a regression line.</strong></h3>
<pre class="r"><code>DAAG::oddbooks %&gt;% 
  mutate(area = (height*weight)) %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(x = log(weight), y = log(area)))+
  geom_smooth(mapping = aes(x = log(weight), y = log(area)),
              method = &quot;lm&quot;,
              formula = &quot;y ~ x&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Area vs Weigth scaterplot&quot;)</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
</div>
<div id="c-which-of-the-lines-a-and-b-gives-the-better-fit" class="section level3">
<h3><strong>c) Which of the lines (a) and (b) gives the better fit?</strong></h3>
<p><strong>A:</strong> In order to evaluate the best fit, I’ll use the metric standard error of the residuals and see which model has a lower value.</p>
<pre class="r"><code>DAAG::oddbooks %&gt;% 
  mutate(volume = (height*breadth*weight),
         area = (height*weight)) %&gt;% 
  lm(formula = &quot;log(volume) ~ log(weight)&quot;) %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = &quot;log(volume) ~ log(weight)&quot;, data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.19855 -0.10268 -0.03917  0.01860  0.40736 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -1.1527     0.8268  -1.394    0.193    
## log(weight)   2.1034     0.1321  15.921 1.97e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1884 on 10 degrees of freedom
## Multiple R-squared:  0.962,  Adjusted R-squared:  0.9582 
## F-statistic: 253.5 on 1 and 10 DF,  p-value: 1.97e-08</code></pre>
</div>
<div id="in-the-data-set-pressure-examine-the-dependence-of-pressure-on-temperature.-the-relevant-theory-is-that-associated-with-the-claudius-clapeyron-equation-by-which-the-logarithm-of-the-vapor-pressure-is-approximately-inversely-proportional-to-the-absolute-temperature." class="section level3">
<h3><strong>5) In the data set <em>pressure</em>, examine the dependence of pressure on temperature. The relevant theory is that associated with the Claudius-Clapeyron equation, by which the logarithm of the vapor pressure is approximately inversely proportional to the absolute temperature.</strong></h3>
<p><strong>A:</strong> Let’s see this data set, plot the graph and the fitted mdoel.</p>
<pre class="r"><code>pressure %&gt;% 
  ggplot2::ggplot()+
  geom_point(mapping = aes(y = log(pressure), x = 1/temperature))+
  geom_smooth(mapping = aes(y = log(pressure), x = 1/temperature),
              method = &quot;lm&quot;,
              formula = &quot;y ~ I(1/x)&quot;,
              se = F,
              lty = 2,
              color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = TeX(&quot;Claudius-Clapeyron equation: $log(p) = \\frac{1}{x}$&quot;),
       y = TeX(&quot;$log(p)$&quot;),
       x = TeX(&quot;$\\frac{1}{x}$&quot;))</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database

## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : font
## family not found in Windows font database</code></pre>
<pre><code>## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database

## Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
## font family not found in Windows font database</code></pre>
<p><img src="/posts/2020-05-14-data-analysis-and-graphs-with-r-john-maindonald-and-john-braun_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>
</div>

            </div>
        </article>

        <hr />

        <div class="post-info">

            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>5991 Words</p>

            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>2020-05-13 21:00 -0300</p>
        </div>

        
    </main>

            </div>

            
                <footer class="footer">
    <div class="footer__inner">
        <div class="footer__content">
            <span>&copy; 2020</span>
            
                <span><a href="/">Francisco Piccolo</a></span>
            
            <span></span>
            <span> <a href="/posts/index.xml" target="_blank" title="rss"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"><path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle></svg></a></span>
        </div>
    </div>
    
    
        <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
        
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                processEscapes: true,
                processEnvironments: true
            },
            // Center justify equations in code and markdown cells. Elsewhere
            // we use CSS to left justify single line equations in code cells.
            displayAlign: 'center',
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}},
                linebreaks: { automatic: true }
            }
        });
        </script>
        

</footer>

            
        </div>

        




<script type="text/javascript" src="/bundle.min.4a69500057d68129e88f497d354afe68422eb56de6d15e45dbe2190858ea5a76bfcb096406f992984b241db45f47388ac57ab0376e3b32125bef7a8a6d0f06c4.js" integrity="sha512-SmlQAFfWgSnoj0l9NUr&#43;aEIutW3m0V5F2&#43;IZCFjqWna/ywlkBvmSmEskHbRfRziKxXqwN247MhJb73qKbQ8GxA=="></script>



    </body>
</html>
