<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>econometria</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 64px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h2 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h3 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h4 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h5 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h6 {
  padding-top: 69px;
  margin-top: -69px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">glass fRog</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="books.html">Books</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa fas fa-code"></span>
     
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="articles_2019.html">2019</a>
    </li>
  </ul>
</li>
<li>
  <a href="random.html">
    <span class="fas fa fas fa-dna"></span>
     
    Random
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/FranciscoPiccolo">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/franciscopiccolo/">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">econometria</h1>

</div>


<div id="exercicio-sobre-autocorrelacao-de-residuos" class="section level3">
<h3>Exercício sobre autocorrelação de resíduos</h3>
<p>Pacotes utilizados para execução das atividades</p>
<pre class="r"><code>library(tidyverse)
library(lmtest)
library(corrplot)
library(readxl)</code></pre>
<p>Objetivos: desenvolver gráficos para analisar autocorrelação de resíduos, aplicar o teste Durbin Watson, aplicar o teste Godfrey e aplicar o teste Q (a.k.a Ljung–Box test).</p>
<div id="primeira-parte" class="section level4">
<h4><strong>Primeira parte</strong></h4>
<p>Base de dados com valores do preço da cana de açucar e área plantada (em hectares), por período analisado. Deseja-se avaliar a elasticidade da área plantada com relação ao preço, a partir de uma série histórica. O modelo é descrito abaixo:</p>
<p><span class="math display">\[ lnY_t = \beta_1+\beta_2 (lnX_t) + U_t \]</span></p>
<p>Onde:</p>
<p><span class="math inline">\(Y_t\)</span> = área plantada no ano t (em hectares)</p>
<p><span class="math inline">\(X_t\)</span> = preço no ano t</p>
<p>Base de dados para o exercício (apenas as primeiras 5 linhas):</p>
<pre><code>## # A tibble: 6 x 3
##   periodo  area  valor
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1       1    29 0.0753
## 2       2    71 0.115 
## 3       3    42 0.101 
## 4       4    90 0.110 
## 5       5    72 0.110 
## 6       6    57 0.132</code></pre>
<p>Gráfico de dispersão (área plantada x preço da cana)</p>
<pre class="r"><code>dados %&gt;% 
  ggplot(aes(x=Área,y=`Preço da Cana de Açúcar`))+
  geom_point()</code></pre>
<p><img src="econometria_files/figure-html/unnamed-chunk-4-1.png" width="288" /></p>
<ol style="list-style-type: decimal">
<li>Verifique se há autocorrelação serial dos erros. Comente o diagrama de dispersão e o correlograma.</li>
</ol>
<p>R: Primeiro, deve-se criar o modelo de regressão para depois gerar os erros. O modelo é resumido abaixo:</p>
<pre><code>## 
## Call:
## lm(formula = area ~ valor, data = dados_2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -97.901 -25.544  -8.999  24.135  99.908 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     2.54      17.77   0.143    0.887    
## valor         479.18      62.95   7.612 1.13e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 39.65 on 32 degrees of freedom
## Multiple R-squared:  0.6442, Adjusted R-squared:  0.6331 
## F-statistic: 57.95 on 1 and 32 DF,  p-value: 1.131e-08</code></pre>
<p>Abaixo há uma amostra dos resíduos gerados pelo modelo:</p>
<pre><code>##   periodo area    valor  residual
## 1       1   29 0.075258 -9.602554
## 2       2   71 0.114894 13.404698
## 3       3   42 0.101075 -8.973524
## 4       4   90 0.110309 34.601735
## 5       5   72 0.109562 16.959682
## 6       6   57 0.132486 -9.025023</code></pre>
<p>Após gerar os resíduos, pode-se analisar se há autocorrelação. Os gráficos abaixo mostram se há este comportamento.</p>
<p><img src="econometria_files/figure-html/unnamed-chunk-8-1.png" width="480" style="display: block; margin: auto;" /></p>
<p><img src="econometria_files/figure-html/unnamed-chunk-9-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Dá para ver que não há autocorrelação entre os resíduos. Porém, para garantir, é interessante usar testes estatísticos formais, como o Durbin Watson ou Godfrey.</p>
<ol start="2" style="list-style-type: decimal">
<li>Aplique o teste de Durbin Watson, escrevendo as hipóteses e testando a autocorrelação. Use um nível de significância de 5%.</li>
</ol>
<p>R: Abaixo há a aplicação do teste DW.</p>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  lr
## DW = 1.4745, p-value = 0.04089
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>De maneira resumida, o valor-p foi de 0.04089 e o valor d, 1.91822. Neste teste, usa-se o valor d para gerar a conclusão do teste. Antes, é preciso trazer os intervalos para comparação deste valor d. Para encontrar o intervalor, use a <a href="http://www.portalaction.com.br/analise-de-regressao/33-diagnostico-de-independencia">tablea</a> específica do teste.</p>
<p>De acordo com a tabela, sabendo a quantidade de registros (n = 33), a significância (0.05) e o nível de liberdade (degrees of freedom = 1) que é o número de variáveis independentes, pode-se achar os valores <strong>dl</strong> e <strong>du</strong>. Para este exercício tem-se:</p>
<p><strong>dl</strong> = 1.35</p>
<p><strong>du</strong> = 1.49</p>
<p>Sabendo que d = 1.91822 e os critérios do teste, pode-se concluir que a hipótese nula é verdadeira, ou seja, não existe autocorrelação. Isso corrobora os gráficos gerados anteriormente.</p>
<ol start="3" style="list-style-type: decimal">
<li>Aplique o teste Breusch Godfrey (a.k.a teste LM) escrevendo as hipóteses. Teste a autocorrelação com nível de significância de 5% e escreva a conclusão.</li>
</ol>
<pre class="r"><code>lmtest::bgtest(lr)</code></pre>
<pre><code>## 
##  Breusch-Godfrey test for serial correlation of order up to 1
## 
## data:  lr
## LM test = 2.0872, df = 1, p-value = 0.1485</code></pre>
<p>O teste godfrey gerou um p valor de 0.1485</p>
<ol start="4" style="list-style-type: decimal">
<li>Aplique o teste Q e comente os resultados.</li>
</ol>
<pre class="r"><code>Box.test(residual,lag = 1,type = c(&quot;Box-Pierce&quot;, &quot;Ljung-Box&quot;), fitdf = 0)</code></pre>
<pre><code>## 
##  Box-Pierce test
## 
## data:  residual
## X-squared = 1.9896, df = 1, p-value = 0.1584</code></pre>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
