---
title: "data_science_and_ml_with_r_course"
output: html_document
---

```{r}
library(tidyverse)
```



```{r}
maybe_square <- function(x){
  if(x%%2 == 0){}
  if(x%%2 == 0){
    x**2
  }
  else {x}
}

maybe_square(4)
```

```{r}
head(mpg)

mpg %>% 
  ggplot(aes(x = displ, y = hwy))+
  geom_point()
```




```{r}
mpg %>%
  ggplot(aes(x=drv,y=hwy))+
  geom_jitter()

mpg %>%
  ggplot(aes(x=drv,y=hwy))+
  geom_boxplot()

mpg %>%
  ggplot(aes(x=drv,y=hwy))+
  geom_violin()+
  geom_jitter()

```



```{r}
mpg %>% 
  ggplot(aes(hwy))+
  geom_freqpoly(binwidth = 1.5)
```




```{r}
data.frame(
  y = c(18,11,16),
  x = c(1:3),
  z = c(1.4,1.8,2.4)
) %>% 
  ggplot(aes(x=x,y=y,ymin = y-z, ymax=y+z))+
  geom_pointrange()
```


```{r}
data.frame(
  y = c(18,11,16),
  x = c(1:3),
  z = c(1.4,1.8,2.4)
) %>% 
  ggplot(aes(x=x,y=y,ymin = y-z, ymax=y+z))+
  geom_errorbar()
```

```{r}
data.frame(
  y = c(18,11,16),
  x = c(1:3),
  z = c(1.4,1.8,2.4)
) %>% 
  ggplot(aes(x=x,y=y,ymin = y-z, ymax=y+z))+
  geom_linerange()+
  geom_point()+
  coord_flip()
```


```{r}
midwest %>% 
  ggplot(aes(x=percwhite,y=percbelowpoverty))+
  geom_point(aes(size=poptotal/1e6))+
  scale_size_area("Population \n (millions)", breaks = c(0.5,1,2,3))
```

```{r}
midwest %>% 
  ggplot(aes(x=percwhite,y=percbelowpoverty))+
  geom_point(aes(size=poptotal/1e6))+
  geom_smooth(aes(weight = poptotal),method = lm,size = 1)+
  scale_size_area("Population \n (millions)")
```


Regressão Linear
```{r}
women

```


ANOVa

Comparação de várias regressões

```{r}
df_1 <- mtcars %>%
  select(am,
        mpg,
        hp)
  
result <- aov(mpg~hp*am,data = mtcars)

result_2 <- aov(mpg~hp+am,data = mtcars)
 
summary(result)
summary(result_2)

anova(result,result_2)
```

Análise de séries temporais

```{r}
rainfall <- c(799,1174.8,865.1,1334.6,635.4,918.5,685.5,998,882,1071)
rainfall.timeseries <- ts(rainfall,start = c(2012,1),frequency = 12)

plot(rainfall.timeseries)
```

Estudo de caso de séries temporais
```{r}
EuStockMarkets

ts_eu <- ts(EuStockMarkets[,1],start = c(1991,130),end = c(1998,169),frequency = 260)

decompose(ts_eu,type = "mult")

plot(decompose(ts_eu,type = "mult"))

install.packages("party")

library(party)

party::ctree()

readingSkills %>% 
  head()

df_dt <- readingSkills[c(1:105),]

dt <- ctree(nativeSpeaker~age+shoeSize+score, data=df_dt) 

plot(dt)
```


```{r}
iris %>%
  head()
```

Random Forest
```{r}
install.packages("randomForest")

library(randomForest)

#randomForest(formula,data)

readingSkills 

forest <- randomForest(nativeSpeaker~age+shoeSize+score, data = readingSkills)

importance(fit,type = 2)


```


Survival Analysis

```{r}
library(survival)
library(tidyverse)

pbc %>% 
  head()

survival::survfit(Surv(pbc$time,pbc$status == 2)~1)

plot(survfit(Surv(pbc$time,pbc$status == 2)~1))
```

Clustering

```{r}
hc <- hclust(dist(sample(1:dim(iris)[1],40)),method = "ave")

plot(hc,hang=-1)

```

K means clustering

```{r}
kmeans(iris,3)
```
















