---
title: "tidytuestady_womens_world_cup"
output: html_document
---

```{r}
library(tidyverse)
library(countrycode)
install.packages("StatsBombR")


wwc_outcomes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/wwc_outcomes.csv')

outcome <- wwc_outcomes %>% 
    left_join(codes,by='team') %>% 
  group_by(year,yearly_game_id) %>% 
  mutate(opposing_score = rev(score)) %>% 
  ungroup() %>% 
  mutate(won_by = score - opposing_score)

squads <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/squads.csv')

codes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/codes.csv')


```



```{r}
wwc_outcomes %>% 
  count(year)

bind_rows()


wwc_outcomes %>% 
  left_join(codes,by='team') %>% 
  filter(year==2019,
         team=='USA'
         )
  

wwc_outcomes
  ggplot(aes(score))+
  geom_histogram()+
  facet_wrap(~win_status)
  
wwc_outcomes %>% 
  filter(year == '2019') %>% 
  count(round,sort=T)

wwc_outcomes %>% 
  filter(year == 2019,team %in% c('USA','NED'))

avg_group_scores <- outcome %>% 
  filter(round == 'Group') %>% 
  group_by(year,team) %>% 
  summarise(
    avg_group_score = mean(score),
    avg_group_won_by = mean(won_by))

outcome %>% 
  inner_join(avg_group_scores,by = c("year","team")) %>% 
  filter(round == "Final") %>% 
  ggplot(aes(country.x,avg_group_won_by,fill=win_status))+
  geom_col()+
  facet_wrap(~year,scales="free_x")+
  labs(title = "dos performance in the group round predict the winner of the finals?",
       sutittle = "yes, in all years except 2011",
       y = "average # of goals the team had won by in the group round",
       x = "country",
       fill = "Result")
```


