---
title: "nobel_prize_analysis"
author: "Francisco_Piccolo"
date: "23 de julho de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(tidyverse)
library(lubridate)
theme_set(theme_light())

nobel_winners <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv') %>% 
  distinct(full_name,prize_year,category,.keep_all=T) %>% 
  mutate(decade=10*(prize_year%/%10),
         age=prize_year-year(birth_date))

nobel_winner_all_pubs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv')
```

```{r,echo=F}
nobel_winners %>% 
  group_by(category,decade) %>% 
  summarise(winners=n(),
            winners_per_year=winners/n_distinct(prize_year)) %>% 
  ggplot(aes(x=decade,y=winners_per_year,color=category))+
  geom_line()+
  expand_limits(y=0)
```

```{r,echo=F}
nobel_winners %>% 
  distinct(full_name,prize_year,category) %>% 
  group_by(full_name) %>% 
  mutate(prizes=n(),
         distinct_prizes=n_distinct(category)) %>% 
  arrange(desc(prizes),full_name)
```


```{r,echo=F}
nobel_winners %>%
  count(decade,
        category,
        gender=coalesce(gender,laureate_type)) %>% 
  group_by(decade,category) %>% 
  ggplot(aes(x=decade,y=n,fill=gender))+
  geom_col()+
  facet_wrap(~category)+
  labs(x='Decade',
       y='# of nobel prize winners',
       fill='Gender',
       title='Nobel Prize gender distribution over time')
```


```{r}
nobel_winners %>% 
  filter(!is.na(age)) %>% 
  group_by(decade,category) %>% 
  summarise(average_age=mean(age),
            median_age=median(age)) %>% 
  ggplot(aes(x=decade,y=average_age,color=category))+
  geom_line()
```

```{r}
nobel_winners %>% 
  filter(!is.na(birth_country)) %>% 
  count(birth_country=fct_lump(birth_country,9),
    category,sort=T) %>% 
  mutate(birth_country=fct_reorder(birth_country,n)) %>% 
  ggplot(aes(birth_country,n,fill=category))+
  geom_col()+
  coord_flip()+
  facet_wrap(~category)
```



```{r}
library(WDI)
library(countrycode)

indicators_raw <- WDI(indicator='NY.GDP.PCAP.CD',
                      start=2016,end=2016,extra=T) %>% 
  
  tbl_df() %>% 
  select(country,
         country_code=iso2c,
         income,
         gdp_per_capita='NY.GDP.PCAP.CD')
  
nobel_winners_countries  <- nobel_winners %>% 
  mutate(country_code=countrycode(birth_country,'country.name','iso2c')) %>% 
  inner_join(indicators_raw,by='country_code') %>% 
  mutate(income=fct_relevel(income,c('low income','lower middle income','upper middle income','high income')))

nobel_winners_countries %>% 
  filter(!is.na(income)) %>% 
  count(category,income) %>% 
  group_by(category) %>% 
  mutate(percent=n/sum(n)) %>% 
  ggplot(aes(x=income,y=percent))+
  geom_col()+
  facet_wrap(~category)+
  coord_flip()+
  labs(x='Current income level of birth country',
       y='% of this category prize')
```



```{r}
winners_summarized <- nobel_winner_all_pubs %>% 
  filter(pub_year<=prize_year) %>% 
  group_by(laureate_id,
           laureate_name,
           category,
           prize_year) %>% 
  summarize(papers_before_prize=n(),
            papers_before_prize_10_year=sum(pub_year>=prize_year-10),
            average_paper_age=median(prize_year-pub_year),
            winning_paper_age=mean((prize_year-pub_year)[is_prize_winning_paper=='YES']
            ))
```


```{r}
winners_summarized %>% 
  group_by(category,
           decade=10*(prize_year%/%10)) %>% 
  summarize(average_papers=mean(papers_before_prize),
            average_paper_age=mean(average_paper_age),
            average_winning_paper_age=mean(winning_paper_age)) %>% 
  ggplot(aes(x=decade,y=average_winning_paper_age,color=category))+
  geom_line()+
  labs(x='prize_year',
       y='time between when paper was published and won prize')
```



scale_y_continuous(labels=scales::percent_format())


