<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.56.3" />


<title>Book Review: Basic Econometrics by Gujaratir and Porter - Francisco Piccolo</title>
<meta property="og:title" content="Book Review: Basic Econometrics by Gujaratir and Porter - Francisco Piccolo">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="/contact/">Contact</a></li>
    
    <li><a href="/library/">Library</a></li>
    
    <li><a href="/post/">Posts</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    

    <h1 class="article-title">Book Review: Basic Econometrics by Gujaratir and Porter</h1>

    

    <div class="article-content">
      


<div id="section" class="section level1 tabset tabset-fade tabset-pills">
<h1></h1>
<div id="overview" class="section level2">
<h2><strong>Overview</strong></h2>
<p>Este livro é a típica “Bíblia” sobre um determinado assunto (i.e. Econometria). Não que não existam outros que também possam ser considerados da mesma forma, porém este é o que vejo com frequência sendo recomendado na parte de bibliografias da matéria de econometria de diversos cursos. Neste livro, os autores buscam explicar a modelagem econométrica de maneira simples e completa, partindo da definição dos termos inerentes à área até os modelos um pouco mais complexos. Ao meu ver, este é um livro de nível básico e intermediário, podendo ser lido por quem ainda não conhece nada sobre econometria.</p>
<p>Logo no início, os autores buscam estabelecer um conceito sobre o que é econometria, chegando as seguintes definições:</p>
<ul>
<li><p><input type="checkbox" disabled="" checked="" />
<strong>Econometria é a aplicação de estatística a dados econômicos</strong></p></li>
<li><p><input type="checkbox" disabled="" checked="" />
<strong>Econometria é a análise quantitativa de fenômenos econômicos</strong></p></li>
</ul>
<p>Também afirmam que a metodologia econométrica se baseia em (i) estabelecimento de uma hipótese; (ii) especificação de um modelo matemático; (iii) obtenção de dados; (iv) estimativa de parâmetros; (v) teste de hipótese; (vi) validção do modelo.</p>
<p>Neste post (como em todos os posts que estão na categoria <strong>library</strong>), irei resumir os capítulos deste livro e resolver alguns exercícios, visando auxiliar pessoas que estejam lendo ele também, pois poderão encontrar a resolução dos exercícios e também a base de dados usadas no meu repositório do git hub.</p>
<div class="figure" style="text-align: center"><span id="fig:pressure"></span>
<img src="C:/Users/francisco.piccolo/Desktop/R/franciscopiccolo.github.io/images/2020-03-03_econometria_basica.png" alt="Capa do livro" width="200px" height="250px" />
<p class="caption">
Figure 1: Capa do livro
</p>
</div>
</div>
<div id="cap.1" class="section level2">
<h2><strong>Cap.1</strong></h2>
<div id="a-natureza-da-análise-de-regressão" class="section level3">
<h3><strong>A natureza da análise de regressão</strong></h3>
<div id="resumo" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>Este é um capítulo introdutório que mostra estabelece alguns pilares da análise de regressão. Primeiro é feito uma definição para o termo regressão, que segundo os autores é <em>o estudo da dependência de uma variável em relação a uma ou mais variáveis explicativas.</em> Também tem-se estabelecido o objetivo da regressão, que é estimar o valor médio da variável dependente usando os valores conhecidos da variável explicativa.</p>
<p>Na sequência, os autores mostram a diferença de relações estatísticas e relações determinísticas, mostrando cenários para cada relação e indicando o por quê da regressão ser tão importante para relações estatísticas. Também é indicada a diferença entre regressão e causação e regressão e correlação.</p>
<p>Por fim, os autores comentam sobre os tipos de dados normalmente presentes nos modelos econométricos. Estes dados são <strong>séries temporais</strong> e <strong>corte transversal</strong>.</p>
</div>
<div id="exercícios" class="section level4">
<h4><strong>Exercícios</strong></h4>
</div>
<div id="traga-os-dados-da-tabela-1.3-sobre-o-índice-de-preço-ao-consumidor-ipc-para-responder-as-alternativas." class="section level4">
<h4><strong>1.1) Traga os dados da tabela 1.3 sobre o índice de preço ao consumidor (IPC) para responder as alternativas.</strong></h4>
<pre class="r"><code>tbl_1.3 &lt;- read.table(file = paste(path,&quot;tabela_1.3_IPC.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;)

# Amostra aleatória dos dados
tbl_1.3[sample(nrow(tbl_1.3),10), ]</code></pre>
<pre><code>##     Ano   EUA Canada Japão França Alemanha Italia Reino.Unido
## 16 1995 152.4  151.4 119.2  148.4    133.3  205.6       175.2
## 2  1981  90.9   85.6  95.3   81.8     92.2   75.5        87.9
## 9  1988 118.3  123.2 105.6  124.3    106.3  141.9       125.6
## 12 1991 136.2  143.1 115.0  137.2    116.3  170.5       156.9
## 22 2001 177.1  169.1 120.1  160.2    144.8  238.3       203.6
## 7  1986 109.6  113.5 104.9  117.2    104.6  128.9       114.9
## 18 1997 160.5  156.3 121.5  153.2    137.8  218.2       185.1
## 21 2000 172.2  164.9 121.0  157.6    142.0  231.9       200.1
## 19 1998 163.0  157.8 122.2  154.2    139.1  222.5       191.4
## 3  1982  96.5   94.9  98.1   91.7     97.0   87.8        95.4</code></pre>
</div>
<div id="a-com-base-nos-dados-forneceidos-calcule-a-taxa-de-inflação-de-cada-país" class="section level4">
<h4><strong>a) Com base nos dados forneceidos, calcule a taxa de inflação de cada país:</strong></h4>
<pre class="r"><code># Taxa de inflação (1985 = 100, até 2005)
ipc_total &lt;- tbl_1.3 %&gt;% 
  filter(Ano %in% c(1985,2005))

ipc_total &lt;- ipc_total[2,2:8]-ipc_total[1,2:8]

knitr::kable(ipc_total, align = &quot;c&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">EUA</th>
<th align="center">Canada</th>
<th align="center">Japão</th>
<th align="center">França</th>
<th align="center">Alemanha</th>
<th align="center">Italia</th>
<th align="center">Reino.Unido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td align="center">87.7</td>
<td align="center">75.9</td>
<td align="center">14.1</td>
<td align="center">58.9</td>
<td align="center">48.9</td>
<td align="center">139.6</td>
<td align="center">114.5</td>
</tr>
</tbody>
</table>
</div>
<div id="b-represente-graficamente-a-taxa-de-inflação-de-cada-país" class="section level4">
<h4><strong>b) Represente graficamente a taxa de inflação de cada país:</strong></h4>
<pre class="r"><code>tbl_1.3 %&gt;%
  tidyr::gather(&quot;campo&quot;, &quot;valor&quot;, 2:8) %&gt;% 
  ggplot(aes(x = Ano, y = valor, group = campo, color = campo))+
  geom_line()+
  theme_graph()+
  labs(title = &quot;Anual inflation for selected countries&quot;,
       x = &quot;&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="a-usando-a-tabela-1.3-represente-as-taxas-de-inflação-do-canará-frança-alemanha-e-itália-japão-e-reino-unido-em-relação-à-taxa-do-eua." class="section level4">
<h4><strong>1.2) a) Usando a tabela 1.3, represente as taxas de inflação do Canará, França, Alemanha e Itália, Japão e Reino Unido em relação à taxa do EUA.</strong></h4>
<pre class="r"><code>can &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = Canada))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()

fra &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = França))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()

ale &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = Alemanha))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()

ita &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = Italia))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()

jap &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = Japão))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()

rei &lt;- tbl_1.3 %&gt;% 
  ggplot(aes(x = EUA, y = Reino.Unido))+
  geom_point(color = graph_color)+
  geom_abline(intercept = 0, color = &quot;red&quot;, lty = 2)+
  theme_graph()


gridExtra::grid.arrange(can,fra,ale,ita,jap,rei,nrow = 2,ncol=3, top = textGrob(&quot;Inflation rate, country vs USA&quot;))</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="a-tabela-abaixo-apresenta-as-taxas-de-câmbio-em-sete-países-industrializados-entre-1985-e-2006." class="section level4">
<h4><strong>1.3) A tabela abaixo apresenta as taxas de câmbio em sete países industrializados, entre 1985 e 2006.</strong></h4>
<pre class="r"><code>tbl_1.4 &lt;- read.table(file = paste(path,&quot;tabela_1.4_cambio.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;,
                      )
  
# Ajustando a coluna do reino unido (1/taxa)
tbl_1.4 &lt;- 
  tbl_1.4 %&gt;% 
  mutate(Reino.unido = 1/Reino.unido)

# Amostra aleatório de 10 valores da tabela
tbl_1.4[sample(nrow(tbl_1.4),10), ]</code></pre>
<pre><code>##     Ano Australia Canada  China  Japao Mexico Coreia.sul  Suecia  Suica
## 17 2001    0.5169 1.5487 8.2770 121.57  9.337    1292.02 10.3425 1.6891
## 2  1986    0.6709 1.3896 3.4616 168.35  0.612     884.60  7.1273 1.7979
## 8  1992    0.7352 1.2085 5.5206 126.78  3.095     784.66  5.8258 1.4064
## 12 1996    0.7828 1.3638 8.3389 108.78  7.600     805.00  6.7082 1.2361
## 16 2000    0.5815 1.4855 8.2784 107.80  9.459    1130.90  9.1735 1.6904
## 11 1995    0.7407 1.3725 8.3700  93.96  6.447     772.69  7.1406 1.1812
## 22 2006    0.7535 1.1340 7.9723 116.31 10.906     954.32  7.3718 1.2532
## 10 1994    0.7316 1.3664 8.6397 102.18  3.385     806.93  7.7161 1.3667
## 6  1990    0.7807 1.1668 4.7921 145.00  2.813     710.64  5.9231 1.3901
## 20 2004    0.7365 1.3017 8.2768 108.15 11.290    1145.24  7.3480 1.2428
##    Reino.unido
## 17   0.6946374
## 2    0.6813381
## 8    0.5661552
## 12   0.6407381
## 16   0.6598047
## 11   0.6335128
## 22   0.5424759
## 10   0.6527841
## 6    0.5605067
## 20   0.5455537</code></pre>
</div>
<div id="a-represente-graficamente-a-evolução-das-taxas-de-câmbio-ao-longo-do-tempo" class="section level4">
<h4><strong>a) Represente graficamente a evolução das taxas de câmbio ao longo do tempo:</strong></h4>
<pre class="r"><code>tbl_1.4 %&gt;% 
  tidyr::gather(&quot;campo&quot;,&quot;valor&quot;,2:10) %&gt;% 
  filter(campo != &quot;Coreia.sul&quot;,
         campo != &quot;Japao&quot;,
         campo != &quot;Suica&quot;,
         campo != &quot;Reino.unido&quot;,
         campo != &quot;Canada&quot;,
         campo != &quot;Australia&quot;
         ) %&gt;% 
  mutate(campo = fct_relevel(campo, levels = c(&quot;Mexico&quot;, &quot;China&quot;, &quot;Suecia&quot;))) %&gt;% 
  ggplot(aes(x = Ano, y = valor,group = campo, color = campo))+
  geom_line(size = 1.2)+
  theme_graph()+
  labs(title = &quot;Exchange rate times serie&quot;,
       x = &quot;&quot;,
       y = &quot;Currency per 1 US$&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>tbl_1.4 %&gt;% 
  tidyr::gather(&quot;campo&quot;,&quot;valor&quot;,2:10) %&gt;% 
  filter(campo %in% c(&quot;Coreia.sul&quot;,&quot;Japao&quot;)) %&gt;%
  ggplot(aes(x = Ano, y = valor, group = campo, color = campo))+
  geom_line(size = 1.2)+
  theme_graph()+
  labs(title = &quot;Exchange rate times serie&quot;,
       x = &quot;&quot;,
       y = &quot;Currency per 1 US$&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>tbl_1.4 %&gt;% 
  tidyr::gather(&quot;campo&quot;,&quot;valor&quot;,2:10) %&gt;% 
  filter(campo %in% c(&quot;Reino.unido&quot;,&quot;Canada&quot;,&quot;Australia&quot;,&quot;Suica&quot;)) %&gt;% 
  mutate(campo = fct_relevel(campo, levels = c(&quot;Suica&quot;, &quot;Canada&quot;, &quot;Australia&quot;, &quot;Reino.unido&quot;))) %&gt;% 
  ggplot(aes(x = Ano, y = valor, group = campo, color = campo))+
  geom_line(size = 1.2)+
  theme_graph()+
  labs(title = &quot;Exchange rate times serie&quot;,
       x = &quot;&quot;,
       y = &quot;Currency per 1 US$&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-7-3.png" width="672" /></p>
</div>
<div id="a-tabela-abaixo-apresenta-o-orçamento-de-publicidade-com-as-impressões-retidas-através-de-uma-pesquisa-feita-com-4-mil-adultos." class="section level4">
<h4><strong>1.7) A tabela abaixo apresenta o orçamento de publicidade com as impressões retidas (através de uma pesquisa feita com 4 mil adultos).</strong></h4>
<pre class="r"><code>tbl_1.6 &lt;- read.table(file = paste(path,&quot;tabela_1.6_publicidade.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;
                      )

# Amostra aleatória dos dados
tbl_1.6[sample(nrow(tbl_1.6),10), ]</code></pre>
<pre><code>##         empresa impressions investment
## 8           MCI        50.7       26.9
## 6     Coca_Cola        78.6       40.1
## 5   Burger_King        60.8       82.4
## 16     Polaroid        38.0       26.9
## 2         Pepsi        99.6       74.1
## 17       Shasta        10.0        5.7
## 19  Oscar_Meyer        23.4        9.2
## 1   Miller_Lite        32.1       50.1
## 14 Calvin_Klein        12.0        5.0
## 18     Meow_Mix        12.3        7.6</code></pre>
</div>
<div id="a-mostre-a-relação-entre-impressões-e-o-investimento-em-publicidade." class="section level4">
<h4><strong>a) Mostre a relação entre impressões e o investimento em publicidade.</strong></h4>
<pre class="r"><code>tbl_1.6 %&gt;% 
  ggplot(aes(x = investment, y = impressions))+
  geom_point(color = graph_color)+
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x, se = F, lty = 20, color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Investment and Impressions relation&quot;,
       x = &quot;Investmnet&quot;,
       y = &quot;Impressions&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="section-1" class="section level2">
<h2><strong>2</strong></h2>
<div id="análise-de-regressão-com-duas-variáveis-algumas-ideias-básicas" class="section level3">
<h3><strong>Análise de regressão com duas variáveis: Algumas ideias básicas</strong></h3>
<div id="resumo-1" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>Neste capítulo, os autores abordam de maneira mais aprofundada o modelo de regressão linear, introduzindo o coneito de <strong>valor esperado de Y</strong> condicional e incondicional. Indica-se que a essência do modelo de regressão é fornecer condições para o valor médio esperado da variável (Y) estudada, ou seja, o modelo de regressão irá gerar uma equação que explicará o valor médio desta variável Y.</p>
<p>Os autores também afirmam que o modelo de regressão buscará <strong>estimar</strong> funções de regressão populacional, fazendo uso de teorias (econômicas) e dados amostrais da população. Existe a função de regressão populacional (sendo apenas uma ideia abstrata) e a função de regressão amostral (que é criada no modelo de regressão), onde a regressão amostral é a responsável por gerar inferências sobre a populacional.</p>
<p>Os modelos lineares deste livro, segundo os autores, serão lineares nas variáveis explicativas (x1, x2, etc), porém podendo não ser lineares nos parâmetros (<span class="math inline">\(\beta\)</span>).</p>
<p>Por fim, os autores comentam sobre os erros estocásticos, que estão sempre presentes no modelo de regressão para representar todas variáveis não incluídas no modelo e ruídos aleatórios que não podem ser mapeados. A não inclusão de algumas variáveis no modelo é explicada no sentido de que isso é algo de certa forma positivo, pois é muito custoso coletar todas as variáveis e o aumento da complexidade do modelo não irá gerar aumento de performance de mesma magnitude. Outra ideia mencionada pelos autores referente aos erros estocásticos se refere à natureza aleatória do ser humano, que impacta a variável estudada <strong>Y</strong> e esta aleatoriedade será descrita nestes erros (<strong><span class="math inline">\(\mu\)</span></strong>).</p>
</div>
<div id="exercícios-1" class="section level4">
<h4><strong>Exercícios</strong></h4>
</div>
<div id="use-a-tabela-abaixo-com-dados-do-eua-sobre-o-mercado-de-trabalho-para-responder-as-seguinter-alternativas." class="section level4">
<h4><strong>2.14) Use a tabela abaixo com dados do EUA sobre o mercado de trabalho para responder as seguinter alternativas.</strong></h4>
<pre class="r"><code>tbl_2.7 &lt;- read.table(file = paste(path,&quot;tabela_2.7_labour_market.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;
                      )

# Amostra dos dados
tbl_2.7[sample(nrow(tbl_2.7),10), ]</code></pre>
<pre><code>##     ano share_men_work_force share_women_work_force unemployment_men
## 23 2002                 74.1                   59.6              5.9
## 14 1993                 75.4                   57.9              7.2
## 16 1995                 75.0                   58.9              5.6
## 22 2001                 74.4                   59.8              4.8
## 24 2003                 73.5                   59.5              6.3
## 3  1982                 76.6                   52.6              9.9
## 15 1994                 75.1                   58.8              6.2
## 5  1984                 76.4                   53.6              7.4
## 20 1999                 74.7                   60.0              4.1
## 21 2000                 74.8                   59.9              3.9
##    unemployment_women avg_hourly_earning_men avg_hourly_earning_women
## 23                5.6                   8.24                    14.95
## 14                6.6                   7.52                    11.03
## 16                5.6                   7.53                    11.64
## 22                4.7                   8.11                    14.53
## 24                5.7                   8.27                    15.35
## 3                 9.4                   7.86                     7.86
## 15                6.0                   7.53                    11.32
## 5                 7.6                   7.95                     8.48
## 20                4.3                   8.00                    13.47
## 21                4.1                   8.03                    14.00</code></pre>
</div>
<div id="a-represente-graficamente-a-relação-entre-a-taxa-de-participação-dos-homens-na-força-de-trabalho-e-a-taxa-de-desemprego-dos-homens." class="section level4">
<h4><strong>a) Represente graficamente a relação entre a taxa de participação dos homens na força de trabalho e a taxa de desemprego dos homens.</strong></h4>
<pre class="r"><code>women_df &lt;- 
  tbl_2.7 %&gt;% 
  select(share_women_work_force,unemployment_women) %&gt;% 
  transmute(
    share_work_force = share_women_work_force,
    unemployment = unemployment_women
  ) %&gt;% 
  mutate(type = &quot;women&quot;)
    
tbl_2.7 %&gt;% 
  select(share_men_work_force,unemployment_men) %&gt;% 
  transmute(
    share_work_force = share_men_work_force,
    unemployment = unemployment_men
  ) %&gt;% 
  mutate(type = &quot;men&quot;) %&gt;% 
  ggplot(aes(x=share_work_force,y=unemployment,color=type))+
  geom_point(color = graph_color)+
  theme_graph()+
  labs(title = &quot;Men&#39;s unemployment and participation rate&quot;,
       x = &quot;Participation rate (%)&quot;,
       y = &quot;Unemployment rate (%)&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="c-represente-graficamente-a-taxa-de-participação-de-homens-e-mulheres-em-relação-ao-ganho-médio-por-hora." class="section level4">
<h4><strong>c) Represente graficamente a taxa de participação de homens e mulheres em relação ao ganho médio por hora.</strong></h4>
<pre class="r"><code>women_df &lt;- 
  tbl_2.7 %&gt;% 
  select(share_women_work_force,avg_hourly_earning_women) %&gt;% 
  transmute(
    share_work_force = share_women_work_force,
    avg_hourly_earning = avg_hourly_earning_women
  ) %&gt;% 
  mutate(type = &quot;women&quot;)

tbl_2.7 %&gt;% 
  select(share_men_work_force,avg_hourly_earning_men) %&gt;% 
  transmute(
    share_work_force = share_men_work_force,
    avg_hourly_earning = avg_hourly_earning_men
  ) %&gt;% 
  mutate(type = &quot;men&quot;) %&gt;% 
  union_all(women_df) %&gt;% 
  ggplot(aes(x=share_work_force,y=avg_hourly_earning,color=type))+
  geom_point()+
  theme_graph()+
  labs(title = &quot;Average hourly wage and participation rate&quot;,
       x = &quot;Participation rate&quot;,
       y = &quot;Hourly wage&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="use-os-dados-da-tabela-2.8-sobre-despesa-com-alimentação-e-despesa-total-em-rupias-de-uma-amostra-de-55-domicílios-da-índia-para-responder-as-alternativas-abaixo." class="section level4">
<h4><strong>2.15) Use os dados da tabela 2.8, sobre despesa com alimentação e despesa total (em rupias), de uma amostra de 55 domicílios da Índia, para responder as alternativas abaixo.</strong></h4>
<pre class="r"><code>tbl_2.8 &lt;- read.table(file = paste(path,&quot;tabela_2.8_despesa_india.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T,
                      dec = &quot;,&quot;)

# Amostra dos dados
tbl_2.8[sample(nrow(tbl_2.8),10), ]</code></pre>
<pre><code>##    alimento total
## 52      450   720
## 50      540   730
## 37      530   790
## 28      350   650
## 34      433   690
## 11      325   525
## 43      446   769
## 38      610   788
## 32      322   677
## 33      540   680</code></pre>
</div>
<div id="a-represente-graficamente-os-dados-colocando-no-eixo-vertical-as-despesas-com-alimentação-e-no-eixo-horizontal-os-gastos-totais-e-em-seguida-insira-uma-linha-de-regressão." class="section level4">
<h4><strong>a) Represente graficamente os dados, colocando no eixo vertical as despesas com alimentação e no eixo horizontal os gastos totais e em seguida, insira uma linha de regressão.</strong></h4>
<pre class="r"><code>tbl_2.8 %&gt;% 
  ggplot(aes(x = total, y = alimento))+
  geom_point(color = graph_color, shape = 20)+
  geom_smooth(method = &quot;lm&quot;, se = F)+
  theme_graph()+
  labs(title = &quot;Food expenditures and total expenditures&quot;,
       x = &quot;Total expenditures&quot;,
       y = &quot;Food expenditures&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="section-2" class="section level2">
<h2><strong>3</strong></h2>
<div id="modelo-de-regressão-de-duas-variáveis-o-problema-da-estimação" class="section level3">
<h3><strong>Modelo de regressão de duas variáveis: o problema da estimação</strong></h3>
<div id="resumo-2" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>O objetivo neste capítulo será estimar a função de regressão populacional (FRP) com base na função de regressão amostral (FRA), da maneira mais precisa possível. Os métodos disponíveis para isso são (i) mínimos quadrados ordinários e (ii) máxima verossimilhança. O método (i) é o mais usado, por ser mais simples, porém ambos geram resultados semelhantes.</p>
<p>Os autores abordarão o método dos mínimos quadrados ordinários no detalhe, explicando como se chega a equação de geração dos parâmetros do modelo de regressão e o motivo por traz do “mínimo” presente no nome do método. Após explicarem as fórmulas do modelo, os autores comentam sobre as prioridades destes estimadores e as hipóteses presentes neste método. Como as hipóteses deste método são importantes para a geração de um modelo confiável, abaixo elas são descritas com maior detalhe.</p>
<p><strong>As hipóteses do método dos mínimos quadrados</strong></p>
<p>Como o objetivo não é só obter os parâmetros (<span class="math inline">\(\beta_1\)</span> e <span class="math inline">\(\beta_2\)</span>) com base em uma amostra, mas sim o de obtê-los e realizar inferências sobre os parâmetros populacionais, se faz neessário estabelecer certas hipóteses a respeito de como a variável explicada / dependente é gerada.</p>
<p>Hipótese 1: O modelo de regressão linear é linear nos parâmeteos <span class="math inline">\(\beta\)</span>, embora possa não ser linear nas variáveis (x), ou seja, o regressando Y e o regressor X podem não ser lineares e o modelo continuará sendo linear.</p>
<p>Hipótese 2: Existência de independência entre as variáveis X e o termo de erro. Esta independência se fundamenta na ideia de que os termos X e <span class="math inline">\(\mu\)</span> possuem influências separadas (e aditivas) sobre Y. Se caso estes termos foram correlacionados, não é possível avaliar efeitos individuais sobre Y. Caso estes termos sejam correlacionados é bem provável que o termo <span class="math inline">\(\mu\)</span> contenha uma variável importante no modelo que não foi incluída.</p>
<p>Hipótese 3: O valor médio do termo de erro <span class="math inline">\(\mu\)</span> deve ser zero. Esta hipótese indica que as variáveis não incluídas no modelo e consequentemente representadas por <span class="math inline">\(\mu\)</span> não devem afetar sistematicamente o valor médio de Y, ou seja, os valores positivos de <span class="math inline">\(\mu\)</span> cancelam os valores negativos. A hipótese 3 implica que não existe erro de especificação ou viés de especificação do modelo, que pode ocorrer quando alguma variável importante deixa de ser mapeada no modelo de regressão ou variáveis irrelevantes são incluídas.</p>
<p>Hipótese 4: Homocedasticidade de <span class="math inline">\(\mu\)</span>. Este hipótese indica que a variância do termo de erro <span class="math inline">\(\mu\)</span> é a mesma independente do valor de X. Homocedasticidade é a constante variância do termo de erro.</p>
<p>Hipótese 5: Não há autocorrelação entre os termos de erro.</p>
<p>Hipótese 6: O número de observações n deve ser maior que o número de parâmetros a serem estimados, ou seja, o número de observações n deve ser maior que o números de variáveis explicativas.</p>
<p>Hipótese 7: Deve haver variabilidade dos valores de X. Isto também implica que não deve haver outliers ou valores discrepantes.</p>
<p>Por fim, há uma explicação sobre as medidas de precisão do modelo de regressão. Sendo elas o erro padrão dos estimadores e pelo coeficiente de determinação (R²) que indica a qualidade do ajuste da reta de regressão. Na mesma problemática de validação da precisão dos estimadores, há a técnica de Monte Carlo, que irá realizar simulações dos parâmetros calculados para verificar a consistência dos resultados e por fim aumentar a confiabilidade do parâmetro.</p>
</div>
<div id="exercícios-2" class="section level4">
<h4><strong>Exercícios</strong></h4>
</div>
<div id="na-tabela-abaixo-consta-a-classificação-de-dez-estudantes-nas-provas-parcial-e-final-de-estatística.-calcule-o-coeficiente-de-correlação-de-ranking-de-spearman-e-interprete-os-resultados." class="section level4">
<h4><strong>3.18) Na tabela abaixo consta a classificação de dez estudantes nas provas parcial e final de estatística. Calcule o coeficiente de correlação de ranking de Spearman e interprete os resultados.</strong></h4>
<pre class="r"><code>df_3.18 &lt;- data.frame(
  prova_parcial = c(1,3,7,10,9,5,4,8,2,6),
  prova_final = c(3,2,8,7,9,6,5,10,1,4)
)

#Amostra aleatória dos dados
df_3.18[sample(nrow(df_3.18),10), ]</code></pre>
<pre><code>##    prova_parcial prova_final
## 1              1           3
## 7              4           5
## 2              3           2
## 4             10           7
## 10             6           4
## 9              2           1
## 8              8          10
## 6              5           6
## 3              7           8
## 5              9           9</code></pre>
<pre class="r"><code># Coeficiente de correlação de spearman
cor.test(df_3.18$prova_parcial,df_3.18$prova_final,method = &quot;spearman&quot;) %&gt;% pander()</code></pre>
<table style="width:92%;">
<caption>Spearman’s rank correlation rho: <code>df_3.18$prova_parcial</code> and <code>df_3.18$prova_final</code></caption>
<colgroup>
<col width="23%" />
<col width="20%" />
<col width="34%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Test statistic</th>
<th align="center">P value</th>
<th align="center">Alternative hypothesis</th>
<th align="center">rho</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">26</td>
<td align="center">0.004459 * *</td>
<td align="center">two.sided</td>
<td align="center">0.8424</td>
</tr>
</tbody>
</table>
</div>
<div id="a-equação-abaixo-mostra-a-relação-entre-a-taxa-de-câmbio-e-a-inflação-para-o-canadá-e-estados-unidos-para-o-período-de-1985-e-2005" class="section level4">
<h4><strong>3.19) A equação abaixo mostra a relação entre a taxa de câmbio e a inflação para o Canadá e Estados Unidos para o período de 1985 e 2005</strong></h4>
<p><span class="math inline">\(\widehat{Y_t} = 0.912 + 2.25X_t\)</span></p>
<p>Onde:</p>
<p><span class="math inline">\(\widehat{Y_t}\)</span> = DC/US$ (taxa de câmbio do Canadá em relação ao Dólar)</p>
<p><span class="math inline">\(X_t\)</span> = inflação americana / inflação do canadá</p>
</div>
<div id="a-interprete-a-regressão" class="section level4">
<h4><strong>a) Interprete a regressão:</strong></h4>
<p>R: A regressão indica que conforme a inflação é maior nos EUA do que no Canadá, a moeda canadense irá se desvalorizar com relação ao dólar, pois a taxa de câmbio (Y) irá aumentar, precisando de mais DC para adquiri um US$. A regressão indica que, dado um período inicial com inflação zero, a taxa de câmbio será de 0.912, ou seja, será necessário DC 0.912 dólar canadense para adquirir 1 dólar americano. O valor de r² de 44% indica que o modelo possui outras variáveis que poderiam auxiliar na explicação desta variação na taxa de câmbio.</p>
</div>
<div id="b-o-valor-positivo-de-x-faz-sentido-econômico" class="section level4">
<h4><strong>b) O valor positivo de X faz sentido econômico?</strong></h4>
<p>R: Acredito que não, pois a inflação maior no EUA deveria reduzir a taxa de câmbio do Canadá e não aumentá-la. Desta forma, o valor de X deveria ser negativo.</p>
</div>
<div id="a-tabela-abaixo-apresenta-dados-do-índice-de-produção-por-hora-x-e-remuneração-real-por-hora-y-para-os-setores-empresarial-e-empresarial-não-agrícola-entre-1960-e-2005.-o-ano-base-é-1992-100." class="section level4">
<h4><strong>3.20) A tabela abaixo apresenta dados do índice de produção por hora (X) e remuneração real por hora (Y) para os setores empresarial e empresarial não agrícola, entre 1960 e 2005. O ano base é 1992 = 100.</strong></h4>
<pre class="r"><code>tbl_3.6 &lt;- read.table(file = paste(path,&quot;tabela_3.6_produtividade_e_salario.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;,
                      )

tbl_3.6[sample(nrow(tbl_3.6),10), ]</code></pre>
<pre><code>##     ano prod_setor_empresarial prod_setor_n_agricola sal_setor_empresarial
## 37 1996                  104.5                 104.7                  99.4
## 24 1983                   83.0                  84.5                  90.3
## 5  1964                   56.8                  59.6                  67.7
## 28 1987                   90.1                  90.6                  95.2
## 17 1976                   77.1                  78.7                  86.4
## 25 1984                   85.2                  86.1                  90.7
## 21 1980                   79.2                  80.6                  89.1
## 10 1969                   65.0                  67.0                  77.3
## 34 1993                  100.4                 100.4                  99.7
## 40 1999                  112.8                 112.5                 108.0
##    sal_setor_n_agricola
## 37                 99.4
## 24                 90.9
## 5                  69.3
## 28                 95.5
## 17                 86.6
## 25                 91.1
## 21                 89.6
## 10                 78.1
## 34                 99.5
## 40                107.5</code></pre>
</div>
<div id="a-represente-graficamente-y-contra-x-para-os-dois-setores-da-economia-separadamente." class="section level4">
<h4><strong>a) Represente graficamente Y contra X para os dois setores da economia separadamente.</strong></h4>
<pre class="r"><code>tbl_3.6 %&gt;% 
  tidyr::gather(&quot;production&quot;,&quot;prod&quot;,2:3) %&gt;% 
  tidyr::gather(&quot;wage&quot;,&quot;wag&quot;,2:3) %&gt;% 
  ggplot()+
  geom_point(aes(x = prod, y = wag, color = production))+
  scale_color_brewer(palette = &quot;Dark2&quot;)+
  geom_smooth(aes(x = prod, y = wag), method = &quot;lm&quot;,se = F)+
  theme_graph()+
  labs(title = &quot;Production index and hourly wages&quot;,
       x = &quot;Production&quot;,
       y = &quot;Wage&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="c-estime-uma-regressão-de-mqo-de-y-contra-x." class="section level4">
<h4><strong>c) Estime uma regressão de MQO de Y contra X.</strong></h4>
<pre class="r"><code>tbl_3.6 %&gt;% 
  tidyr::gather(&quot;production&quot;,&quot;X&quot;,2:3) %&gt;% 
  tidyr::gather(&quot;wage&quot;,&quot;Y&quot;,2:3) -&gt; df_tbl_3.6

summary(lm(Y~X, data = df_tbl_3.6)) %&gt;% pander()</code></pre>
<table style="width:90%;">
<colgroup>
<col width="25%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">32.63</td>
<td align="center">0.7125</td>
<td align="center">45.8</td>
<td align="center">7.626e-102</td>
</tr>
<tr class="even">
<td align="center"><strong>X</strong></td>
<td align="center">0.6699</td>
<td align="center">0.007976</td>
<td align="center">83.99</td>
<td align="center">1.675e-147</td>
</tr>
</tbody>
</table>
<table style="width:88%;">
<caption>Fitting linear model: Y ~ X</caption>
<colgroup>
<col width="20%" />
<col width="30%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Observations</th>
<th align="center">Residual Std. Error</th>
<th align="center"><span class="math inline">\(R^2\)</span></th>
<th align="center">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">184</td>
<td align="center">2.37</td>
<td align="center">0.9749</td>
<td align="center">0.9747</td>
</tr>
</tbody>
</table>
</div>
<div id="a-tabela-abaixo-mostra-o-preço-do-ouro-o-índice-nyse-e-o-índice-ipc-entre-1974-e-2006.-use-a-para-responder-as-alternativas-abaixo" class="section level4">
<h4><strong>3.22) A tabela abaixo mostra o preço do ouro, o índice NYSE e o índice IPC entre 1974 e 2006. Use-a para responder as alternativas abaixo:</strong></h4>
<pre class="r"><code>tbl_3.7 &lt;- read.table(file = 
                      paste(path,&quot;tabela_3.7_ouro_nyse_IPC.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;,
                      )

# Amostra aleatória dos dados
tbl_3.7[sample(nrow(tbl_3.7),10), ]</code></pre>
<pre><code>##     ano gold_price nyse_index ipc_index
## 3  1976     124.84     575.85      56.9
## 31 2004     409.72    6612.62     188.9
## 14 1987     446.46    1709.79     113.6
## 1  1974     159.26     463.54      49.3
## 28 2001     274.04    6397.85     177.1
## 17 1990     383.51    1939.47     130.7
## 30 2003     363.38    5447.46     184.0
## 23 1996     387.77    3787.20     156.9
## 5  1978     193.22     567.81      65.2
## 32 2005     444.74    7349.00     195.3</code></pre>
</div>
<div id="a-assinale-em-um-mesmo-diagrama-de-dispersão-os-preços-do-ouro-o-ipc-e-o-índice-nyse." class="section level4">
<h4><strong>a) Assinale, em um mesmo diagrama de dispersão, os preços do ouro, o IPC e o índice NYSE.</strong></h4>
<pre class="r"><code>tbl_3.7 %&gt;% 
  transmute(x = gold_price,
         y = nyse_index,
         z = ipc_index) -&gt; df_test

x &lt;- df_test$x
y &lt;- df_test$y
z &lt;- df_test$z
  
plot3D::scatter3D(x, y, z, 
                  colvar = NULL, 
                  add = FALSE, 
                  col = &quot;blue&quot;, 
                  pch = 19, 
                  phi = 20, 
                  theta = 20, 
                  cex = .9, 
                  bty = &quot;b2&quot;, 
                  expand = .9, 
                  col.grid = &quot;darkblue&quot;, 
                  col.panel = &quot;steelblue&quot;, 
                  colkey = T, 
                  main = &quot;Table 3.7 data&quot;, 
                  xlab = &quot;gold_price&quot;, 
                  ylab = &quot;nyse_index&quot;, 
                  zlab = &quot;ipc_index&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="b-supõe-se-que-um-investimento-funcione-como-proteção-contra-a-inflação-se-seu-preço-ou-sua-taxa-de-retorno-acompanha-pelo-menos-a-taxa-de-inflação.-para-testar-esta-hipótese-ajuste-o-seguinte-modelo-supondo-que-o-diagrama-de-dispersão-elaborado-no-item-a-seja-adequado." class="section level4">
<h4><strong>b) Supõe-se que um investimento funcione como proteção contra a inflação se seu preço ou sua taxa de retorno acompanha, pelo menos, a taxa de inflação. Para testar esta hipótese, ajuste o seguinte modelo, supondo que o diagrama de dispersão elaborado no item (a) seja adequado.</strong></h4>
<p><span class="math display">\[gold.price = \beta_1 + \beta_2 + IPC + \mu\]</span>
<span class="math display">\[NYSE.index = \beta_1 + \beta_2 + IPC + \mu\]</span>
R: Para testar está hipótese se faz necessário analisar a taxa de variação destes indicadores e ver se a variação do outro e do índice NYSE fica acima da variação do IPC, que representa a inflação para o consumidor.</p>
<pre class="r"><code>tbl_3.7 %&gt;% 
  mutate(gold_price_var = round(gold_price/lag(gold_price, 1, default = NA), digits = 8)-1,
         nyse_index_var = round(nyse_index/lag(nyse_index, 1, default = NA), digits = 8)-1,
         ipc_index_var = round(ipc_index/lag(ipc_index, 1, default = NA), digits = 8)-1) %&gt;% 
  filter(!is.na(gold_price_var)) -&gt; tbl_3.7_df_adj
  
# Modelo 1, gold_price ~ ipc_index
tbl_3.7_df_adj %&gt;% lm(formula = gold_price_var ~ ipc_index_var) %&gt;% pander()</code></pre>
<table style="width:90%;">
<caption>Fitting linear model: gold_price_var ~ ipc_index_var</caption>
<colgroup>
<col width="27%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">-0.1147</td>
<td align="center">0.07197</td>
<td align="center">-1.594</td>
<td align="center">0.1215</td>
</tr>
<tr class="even">
<td align="center"><strong>ipc_index_var</strong></td>
<td align="center">3.96</td>
<td align="center">1.337</td>
<td align="center">2.962</td>
<td align="center">0.005932</td>
</tr>
</tbody>
</table>
<pre class="r"><code>tbl_3.7_df_adj %&gt;% 
  ggplot()+
  geom_point(aes(x = ipc_index_var, y = gold_price_var), color = graph_color)+
  geom_abline(lty = 2, color = &quot;dark orange&quot;, alpha = .7)+
  geom_smooth(aes(x = ipc_index_var, y = gold_price_var), method = &quot;lm&quot;, formula = y ~ x)+
  geom_hline(yintercept = 0, lty = 2, color = &quot;red&quot;, alpha = .8)+
  expand_limits(x = 0, y = 0)+
  scale_x_continuous(labels = scales::percent)+
  scale_y_continuous(labels = scales::percent)+
  theme_graph()+
  labs(title = &quot;Gold price and IPC index year variation&quot;,
       x = &quot;IPC index variation&quot;,
       y = &quot;Gold price variation&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code># Modelo 2, nyse_index ~ ipc_index
tbl_3.7_df_adj %&gt;% lm(formula = nyse_index_var ~ ipc_index_var) %&gt;% pander()</code></pre>
<table style="width:90%;">
<caption>Fitting linear model: nyse_index_var ~ ipc_index_var</caption>
<colgroup>
<col width="27%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">0.1213</td>
<td align="center">0.03777</td>
<td align="center">3.21</td>
<td align="center">0.003156</td>
</tr>
<tr class="even">
<td align="center"><strong>ipc_index_var</strong></td>
<td align="center">-0.4604</td>
<td align="center">0.7017</td>
<td align="center">-0.6561</td>
<td align="center">0.5168</td>
</tr>
</tbody>
</table>
<pre class="r"><code>tbl_3.7_df_adj %&gt;% 
  ggplot()+
  geom_point(aes(x = ipc_index_var, y = nyse_index_var), color = graph_color)+
  geom_abline(lty = 2, color = &quot;dark orange&quot;, alpha = .7)+
  geom_smooth(aes(x = ipc_index_var, y = nyse_index_var), method = &quot;lm&quot;, formula = y ~ x)+
  geom_hline(yintercept = 0, lty = 2, color = &quot;red&quot;, alpha = .8)+
  expand_limits(x = 0, y = 0)+
  scale_x_continuous(labels = scales::percent)+
  scale_y_continuous(labels = scales::percent)+
  theme_graph()+
  labs(title = &quot;NYSE index and IPC index year variation&quot;,
       x = &quot;IPC index variation&quot;,
       y = &quot;NYSE index variation&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<p>Aparentemente, o ouro é um ativo mais interessante para edge do que o índice NYSE, porém há dois outliers do preço do ouro que está fazendo a regressão gerar um parâmetro positivo.</p>
</div>
</div>
</div>
<div id="section-3" class="section level2">
<h2><strong>4</strong></h2>
<div id="modelo-clássico-de-regressão-linear-normal" class="section level3">
<h3><strong>Modelo clássico de regressão linear normal</strong></h3>
<div id="resumo-3" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>Este capítulo é focado no modelo clássico de regressão linear normal que introduz o conceito de distribuição normal dos termos de erro. A ideia é que, como dito anteriormente, o objetivo do modelo de regressão é gerar estimadores (<span class="math inline">\(\hat{\beta}\)</span>) para o parâmetro populacional (<span class="math inline">\(\beta\)</span>) e como se está falando sobre estimadores, conclui-se que eles irão variar de amostra para amostra, ou seja, são variáveis aleatórias que deverão seguir alguma distribuição de probabilidade.</p>
<p>Quando se indica que os estimadores devem seguir uma distribuição de probabilidade, a mais cogitada é a normal. Para afirmar que os estimadores seguirão a distribuição normal, os autores mostrma algebricamente que os estimadores seguem uma função linear do termo de erro <span class="math inline">\(\mu\)</span> e sabendo que quando uma variável é uma função linear de outra que segue comportamento aleatório e com distribuição normal, pode-se assumir que a primeira também terá comportamento aleatório de mesma distribuição. Desta forma, cria-se a hipótese de normalidade dos resíduos (a.k.a termo de erro <span class="math inline">\(\mu\)</span>) e consequentemente a hipótese de normalidade dos estimadores (<span class="math inline">\(\hat{\beta}\)</span>), que embasará inferências (teste de hipóteses e intervalos de confiança), pilar fundamental do modelo clássico.</p>
<p>A hipótese de normalidade dos resíduos, pode ser fundamentado no <strong>teorema do limite central</strong>. Pelo fato de que os resíduos representam diversas variáveis não inclusas no modelo, há a ideia de que quando diversas variáveis são representadas por uma únida e suas distribuições de probabilidade consolidadas (somadas), o resultado será uma distribuição normal. Ao formar esta hipótese do modelo, pode-se realizar testes estatísticos (t, F, x²) dos estimadores para inferir sobre o verdadeiro valor dos parâmetros populacionais.</p>
</div>
</div>
</div>
<div id="section-4" class="section level2">
<h2><strong>5</strong></h2>
<div id="a-regressão-de-duas-variáveis-estimação-de-intervalo-e-teste-de-hipóteses" class="section level3">
<h3><strong>A regressão de duas variáveis: estimação de intervalo e teste de hipóteses</strong></h3>
<div id="resumo-4" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>Após entender as premissas do modelo clássico de regressão linear no capítulo anterior os autores neste capítulo desenvolvem o modelo de regressão completo para realizar estimativas e inferências sobre os estimadores estudados (<span class="math inline">\(\hat{\beta_1}\)</span> e <span class="math inline">\(\hat{\beta_2}\)</span>).</p>
<p>Antes de iniciar no desenvolvimento das estimativas e validação de sua acertividade, os autores indicam a premissa de que o valor esperado dos estimadores são o verdadeiro parâmetro populacional, ou seja <span class="math inline">\(e(\hat{\beta}) = \beta\)</span>. Outro ponto indicado é que a medida de confiabilidade para um estimdor é seu erro padrão. Conhecendo estas premissas, pode-se executar o modelo e validar as estimativas. A validação das estimativas é apresentada das seguintes formas:</p>
<p><strong>1. Intervalo de confiança:</strong> Neste método, é feita a construção de intervalos de confiança, podendo ocorrer de duas formas. Uma quando se conhece a variância populacional, usando a distribuição normal para gerar os valores críticos e outra quando não se conhece a variância populacional, devendo neste caso usar a distribuição t. Em ambos os casos, a amplitude do intervalo será proporcional ao erro padrão dos estimadores.</p>
<p>A fórmula abaixo mostra o cálculo do intervalo para cada cenário:</p>
<p><strong>Variância conhecida, usa-se tabela z:</strong> <span class="math inline">\(\hat{\beta} + ou - (z_\frac{\alpha}{2} \times ep(\hat{\beta}))\)</span></p>
<p><strong>Variância desconhecida, usa-se tabela t:</strong> <span class="math inline">\(\hat{\beta} + ou - (t_\frac{\alpha}{2} \times ep(\hat{\beta}))\)</span></p>
<p>A proposta deste método é que, ao se construírem vários intervalos (usando diferentes amostras de dados, que gerarão diferentes estimatores e diferentes erros padrão), o parâmetro populacional estará contido em (<span class="math inline">\(1-\alpha\)</span>) dos casos. A variável <span class="math inline">\(\alpha\)</span> é chamada de nível de significância e o valor <span class="math inline">\(1-\alpha\)</span> é o coeficiente de confiança. Por exemplo, se <span class="math inline">\(\alpha\)</span> for 5%, o coeficiente de confiança será de 95%, neste caso, se forem construídos 100 intervalos, o parâmetro populacional <span class="math inline">\(\beta\)</span> estará contido em 95 intervalos. Não dá pra saber em qual intervalo o parâmetro estará, pois é uma variável desconhecida, porém a confiança (de 95%) é dada ao processo de criação dos intervalos.</p>
<p><strong>2. Teste de hipóteses:</strong> Este modo pode usar o intervalo de confiança visto anteriormente ou usar o teste de significância, que virá junto com o uso do <strong>valor-p</strong>. O ponto inicial deste método é estabelecer uma hipótese nula e uma alternativa. A hipótese nula, para modelos de regressão, é indicar que o estimador (<span class="math inline">\(\hat{\beta}\)</span>) é igual a zero e a alternativa é de que o estimador é diferente de zero.</p>
<p>No caso de se usar o intervalo de confiança, se o intervalo não conter a hipótese nula, ela poderá ser rejeitada. Por exemplo, se H0: <span class="math inline">\(\beta_2 = 0\)</span> e H1: <span class="math inline">\(\beta_2 \neq 0\)</span> e o intervalo gerado seja [<span class="math inline">\(2\leq \beta_2 \leq 4\)</span>], pode-se rejeitar H0.</p>
<p>Ao se optar pelo teste de significância, o objetivo será encontrar o valor crítico de <strong>z</strong> ou <strong>t</strong> (caso se conheça ou não a variância populacional). Ao encontrar o valor crítico, basta usar a tabela destas distribuições (tabela <strong>z</strong> ou <strong>t</strong>) e ver a probabilidade de se conseguir o valor crítico encontrado. Caso a probabilidade seja abaixo do nível de significância escolhido (e.g. 5%), será possível rejeitar H0. A probabilidade de se chegar neste valor crítico é o <strong>valor-p</strong>, que indica a probabilidade de se rejeitar H0 incorretamente, que também é chamado de probabilidade de se cometer o <strong>erro tipo I</strong>.</p>
<p>A proposta do teste de hipótese é buscar rejeitar H0, esta hipótese não poderá ser aceita, pois o parâmetro populacional não é conhecido. Se não for possível rejeitar H0, apenas pode-se concluir que os resultados foram inconclusivos e que se falhou em rejeitar H0.</p>
<p>Ao finalizarem a explicação sobre inferência e estimativas, os autores dão sequência com a explicação da análise de variância (a.k.a ANOVA). Esta análise, quando aplicada ao modelo de regressão, buscará mostrar a variabilidade de cada estimador do modelo e ver o quanto estas variabilidades explicam a variabilidade total da variável dependente (<span class="math inline">\(\hat{y}\)</span>). A ANOVA também apresentará a variável <strong>F</strong>, que será útil em modelos de regressão múltiplos.</p>
<p>Após explicarem sobre a análise de variância, os autores indicam uma forma de apresentar o resultado final do modelo de regressão. A indicação é de que deve-se primeiro mostrar a equação desenvolvida, em seguida os erros padrão e o R², na sequência mostra-se os valores críticos t (ou z) e por fim a variável F (em modelos de apenas duas variáveis (intercepto e inclinação) esta estatística não é relevante).</p>
<p>Tendo apresentado os resultados do modelo, é importante mostrar que a premissa de normalidade dos resíduos se confirma. Para isso, os autores indicam o histograma, o gráfico qq-plot e o teste Jarque-Bera.</p>
</div>
<div id="exercícios-3" class="section level4">
<h4><strong>Exercícios</strong></h4>
</div>
<div id="consulte-a-regressão-da-demanda-por-telefones-celulares-na-equação-3.7.3" class="section level4">
<h4><strong>5.3) Consulte a regressão da demanda por telefones celulares na Equação (3.7.3)</strong></h4>
</div>
<div id="a-o-coeficiente-de-intercepto-estimado-é-significativo-no-nível-de-5-de-significância-qual-é-a-hipótese-nula-subjacente" class="section level4">
<h4><strong>a) O coeficiente de intercepto estimado é significativo no nível de 5% de significância? Qual é a hipótese nula subjacente?</strong></h4>
<p>A regressão indicada pelo problema é: <span class="math inline">\(\hat{Y} = 14.47+0.0022X\)</span> onde ep(<span class="math inline">\(\beta_1\)</span>) = 6.1523 ep(<span class="math inline">\(\beta_2\)</span>) = 0.00032 e r² = 0.6023</p>
<p>Como a questão visa avaliar se o intercepto é significativo, deve-se analisar se ele é diferente de zero. Neste caso H0: <span class="math inline">\(\beta_1\)</span> = 0 e H1: <span class="math inline">\(\beta_1 \neq 0\)</span>. Para testar esta hipótese, será optado pelo valor-p, que será obtido através do cálculo do valor crítico t.</p>
<p>valor-t = <span class="math inline">\(\frac{\hat{\beta_1}-\beta_1}{ep(\hat{\beta_1})}\)</span> = <span class="math inline">\(\frac{14,47-0}{6.1523} = 2.35\)</span></p>
<p>Dado um nível de significância de 5% e 34 gl, o valor-p para este valor crítico t é de 2.4%, abaixo do limite estimado. Desta forma, pode-se rejeitar H0 e concluir que o intercepto é significativo.</p>
<pre class="r"><code># Valor-p calculado com o valor t obtido anteriormente
(1-pt(2.35, 36))*2</code></pre>
<pre><code>## [1] 0.02437449</code></pre>
</div>
<div id="b-o-coeficiente-angular-estimado-é-significativo-no-nível-de-5-de-significância-qual-a-hipótese-nula-subjacente" class="section level4">
<h4><strong>b) O coeficiente angular estimado é significativo no nível de 5% de significância? Qual a hipótese nula subjacente?</strong></h4>
<p>Nesta questão, a solução segue a mesma abordagem da anterior. Busca-se saber se o coeficiente é significativo, desta forma a hipótese nula (H0) será H0: <span class="math inline">\(\beta_2 = 0\)</span> e H1: <span class="math inline">\(\beta_2 \neq 0\)</span>. Refazendo os cálculos, alterando os valores, temos:</p>
<p>valor-t: <span class="math inline">\(\frac{0.0022}{0.00032} = 6.88\)</span></p>
<p>É um valor-t bastante alto, provavelmente H0 será rejeitada apenas pela magnitude do valor. O valor-p deste valor-t é muito baixo, portanto pode-se de fato rejeitar H0 e concluir que o coeficiente angular também é significativo.</p>
<pre class="r"><code># Valor-p calculado com o valor t obtido anteriormente
(1-pt(6.88,36))*2</code></pre>
<pre><code>## [1] 4.719422e-08</code></pre>
</div>
<div id="o-que-se-conhece-por-linha-característica-na-análise-moderna-de-investimentos-nada-mais-é-do-que-a-regressão-obtida-por-meio-do-seguinte-modelo" class="section level4">
<h4><strong>5.5) O que se conhece por linha característica na análise moderna de investimentos nada mais é do que a regressão obtida por meio do seguinte modelo:</strong></h4>
<p><span class="math inline">\(r_t = \alpha+\beta\times r_m+\mu_t\)</span></p>
<p>Onde:</p>
<p><span class="math inline">\(r_t =\)</span> taxa de retorno do ativo no período t</p>
<p>$r_m = $ taxa de retorno do portfólio de mercado no período t</p>
<p>$_t = $ termo de erro estocástico</p>
<p>Neste modelo, <span class="math inline">\(\beta\)</span> é conhecido como coeficiente beta do ativo, representando uma medida de risco. Com este modelo, dois autores estudaram a taxa de retorno mensal para as ações da IBM e chegaram ao seguinte modelo.</p>
<p><span class="math inline">\(\hat{r_t} = 0.7264+1.0598r_m\)</span> com ep(0.3001) e ep(0.0728) respectivamente.</p>
</div>
<div id="a-diz-se-que-um-ativo-cujo-coeficiente-beta-é-maior-que-um-é-um-papel-volátil.-as-ações-da-ibm-foram-voláteis-no-estudo-realizado" class="section level4">
<h4><strong>a) Diz-se que um ativo cujo coeficiente beta é maior que um é um papel volátil. As ações da IBM foram voláteis no estudo realizado?</strong></h4>
<p>Sim, visto que o coeficiente beta ficou em 1.0598.</p>
</div>
<div id="b-o-coeficiente-do-intercepto-é-significativamente-diferente-de-zero-se-for-qual-o-significado-prático-disso" class="section level4">
<h4><strong>b) O coeficiente do intercepto é significativamente diferente de zero? Se for, qual o significado prático disso?</strong></h4>
<p>O intercepto estimado é de 0.7264, com um erro padrão de 0.3001. Para ver se este valor é significativo, deve-se estabelecer um nível de confiança e uma hipótese nula. Para este caso, H0 será <span class="math inline">\(\beta_1 = 0\)</span> e H1 <span class="math inline">\(\beta_1 \neq 0\)</span>. Tendo o nível de significância e os graus de liberdade, pode-se chegar ao valor-p após calcular o valor crítico t.</p>
<pre class="r"><code># Valor crítico t
# Intercepto estimado dividido pelo erro padrão
valor_t &lt;- 0.7264/0.3001

# Como o teste é bilateral, deve-se multiplicar o valor-p por 2
(1-pt(valor_t, 238))*2</code></pre>
<pre><code>## [1] 0.01624765</code></pre>
<p>O valor-p para o intercepto ficou em 1.62%, abaixo do limite de confiança, indicando que este estimador é estatísticamente significativo a 5% de nível de confiança.</p>
</div>
<div id="a-tabela-5.5-apresenta-dados-sobre-a-remuneração-anual-salário-médio-em-dólares-dos-professores-e-as-despesas-por-aluno-das-escolas-em-dólares-no-ano-de-1985-em-50-estados-e-no-distrito-de-columbia.-para-verificar-se-há-alguma-relação-entre-a-remuneração-dos-professores-e-as-despesas-por-aluno-nas-escolas-públicas-sugeriu-se-o-seguinte-modelo" class="section level4">
<h4><strong>5.9) A tabela 5.5 apresenta dados sobre a remuneração anual (salário médio em dólares) dos professores e as despesas por aluno das escolas (em dólares) no ano de 1985 em 50 estados e no distrito de Columbia. Para verificar se há alguma relação entre a remuneração dos professores e as despesas por aluno nas escolas públicas, sugeriu-se o seguinte modelo:</strong></h4>
<p><span class="math inline">\(r = \beta_1+\beta_2\times g + \mu\)</span></p>
<p>r = renda dos professores
g = despesas por aluno</p>
<pre class="r"><code># Tabela 5.5
tbl_5.5 &lt;- read.table(file = 
                      paste(path,&quot;tabela_5.5_salario_medio_anual_e_despesa_por_aluno.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;.&quot;,
                      )

# Amostra aleatória dos dados
tbl_5.5[sample(nrow(tbl_5.5),10), ]</code></pre>
<pre><code>##    obs   wage expense
## 31  31 20.940    2853
## 13  13 30.168    3782
## 50  50 41.480    8349
## 9    9 25.853    4168
## 23  23 27.186    4349
## 41  41 27.224    5440
## 20  20 20.939    3285
## 12  12 27.170    3621
## 28  28 21.570    2920
## 46  46 25.610    2932</code></pre>
</div>
<div id="a-represente-graficamente-os-dados-e-trace-uma-linha-de-regressão" class="section level4">
<h4><strong>a) Represente graficamente os dados e trace uma linha de regressão</strong></h4>
<pre class="r"><code>tbl_5.5 %&gt;% 
  ggplot()+
  geom_point(mapping = aes(x = expense, y = wage), color = graph_color)+
  geom_smooth(mapping = aes(x = expense, y = wage), method = &quot;lm&quot;, formula = y~x, se = F, lty = 2, color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Teachers income and students expenditures relation&quot;,
       x = &quot;Students expenses&quot;,
       y = &quot;Teachers income&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="b-suponha-que-com-base-em-a-você-decida-estimar-o-modelo-de-regressão-anterior.-obtenha-as-estimativas-dos-parâmetros-os-erro-padrão-r²-sqr-e-sqe." class="section level4">
<h4><strong>b) Suponha que, com base em (a), você decida estimar o modelo de regressão anterior. Obtenha as estimativas dos parâmetros, os erro padrão, r², SQR e SQE.</strong></h4>
<pre class="r"><code>tbl_5.5 %&gt;%
  lm(formula = wage~expense) %&gt;% summary() %&gt;% 
  pander::pander()</code></pre>
<table style="width:89%;">
<colgroup>
<col width="25%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">12.13</td>
<td align="center">1.197</td>
<td align="center">10.13</td>
<td align="center">1.308e-13</td>
</tr>
<tr class="even">
<td align="center"><strong>expense</strong></td>
<td align="center">0.003308</td>
<td align="center">0.0003117</td>
<td align="center">10.61</td>
<td align="center">2.707e-14</td>
</tr>
</tbody>
</table>
<table style="width:88%;">
<caption>Fitting linear model: wage ~ expense</caption>
<colgroup>
<col width="20%" />
<col width="30%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Observations</th>
<th align="center">Residual Std. Error</th>
<th align="center"><span class="math inline">\(R^2\)</span></th>
<th align="center">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">51</td>
<td align="center">2.325</td>
<td align="center">0.6968</td>
<td align="center">0.6906</td>
</tr>
</tbody>
</table>
<p>Com base no output do modelo, pode-se criar a equação estimada para os parâmetros populacionais:</p>
<p><span class="math inline">\(\hat{r} = \hat{\beta_1}+\hat{\beta_2}\times g+\mu\)</span></p>
<p><span class="math inline">\(\hat{r} = 12.13+0.003308\times g+\mu\)</span></p>
<p>Com a equação acima, pode-se ver a estimativa dos parâmetros (<span class="math inline">\(\hat{\beta_1}\)</span> e <span class="math inline">\(\hat{\beta_2}\)</span>). O R² ficou em 69.68% e SQR e SQE serão obtidos com o output da ANOVA demonstrada abaixo.</p>
<pre class="r"><code>#Anova do modelo de regressão
anova(tbl_5.5 %&gt;%
  lm(formula = wage~expense)) %&gt;% pander::pander()</code></pre>
<table style="width:86%;">
<caption>Analysis of Variance Table</caption>
<colgroup>
<col width="22%" />
<col width="6%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>expense</strong></td>
<td align="center">1</td>
<td align="center">608.6</td>
<td align="center">608.6</td>
<td align="center">112.6</td>
<td align="center">2.707e-14</td>
</tr>
<tr class="even">
<td align="center"><strong>Residuals</strong></td>
<td align="center">49</td>
<td align="center">264.8</td>
<td align="center">5.405</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="c-interprete-os-resultados-da-regressão.-faz-sentido-do-ponto-de-vista-econômico" class="section level4">
<h4><strong>c) Interprete os resultados da regressão. Faz sentido do ponto de vista econômico?</strong></h4>
<p>A regressão faz sentido, visto que o salário dos professores está diretamente atrelado ao gasto com estudo dos alunos e também o intercepto é relevante visto que há um salário mínimo dado pelo governo ao professores que não irá depender do gasto dos alunos.</p>
</div>
<div id="d-estabeleça-um-intervalo-de-confiança-de-95-para-o-estimador-beta-2.-você-rejeitaria-a-hipótese-de-que-o-verdadeiro-coeficiente-angular-é-3" class="section level4">
<h4><strong>d) Estabeleça um intervalo de confiança de 95% para o estimador beta 2. Você rejeitaria a hipótese de que o verdadeiro coeficiente angular é 3?</strong></h4>
<p>Para testar a hipótese, deve estabelecer uma hipótese nula e uma alternativa. H0 será o valor de <span class="math inline">\(\beta_2\)</span> proposto pela questão, ou seja, H0: <span class="math inline">\(\beta_2 = 3\)</span> e H1: <span class="math inline">\(\beta_2 \neq 3\)</span>. Ao contruir o intervalo, caso o valor 3 esteja dentro dele, não será possível rejeitar H0. Caso fique fora do intervalo, H0 poderá ser rejeitada. O intervalo será construído com o uso do erro padrão e da distribuiçaõ t, que irá fornecer um valor crítico de t para construção dos limites do intervalo.</p>
<p>Conforme visto anteriormente, os limites são construídos através da fórmula:</p>
<p><span class="math inline">\(\hat{\beta_2} + t_\frac{\alpha}{2} \times ep(\hat{\beta_2})\)</span></p>
<p>Lembrando que se faz <span class="math inline">\(\frac{\alpha}{2}\)</span> por ser um teste bicaudal, ou seja <span class="math inline">\(H0 = X\)</span> e <span class="math inline">\(H1 \neq X\)</span>. Se caso fosse algo do tipi <span class="math inline">\(H0 \leq X\)</span> e <span class="math inline">\(H1 &gt; X\)</span>, seria um teste unicaudal e <span class="math inline">\(\alpha\)</span> não seria dividido por 2.</p>
<p>Para resolver a equação acima, é necessário obter o valor do estimador de <span class="math inline">\(\beta_2\)</span> (dado no resultado do modelo de regressão da equação do item (b)), o erro padrão deste estimador (também fornecido no output anterior) e o valor crítico t, que pode ser obtido através do R pela fórmula abaixo.</p>
<pre class="r"><code># Valor crítico de t para criar o intervalo
qt(0.975, df = 49)</code></pre>
<pre><code>## [1] 2.009575</code></pre>
<p>Desta forma, tem-se:</p>
<p><span class="math inline">\(\hat{\beta_2} = 0.003308\)</span></p>
<p><span class="math inline">\(ep(\hat{\beta_2}) = 0.0003117\)</span></p>
<p>Valor t = 2.009575</p>
<p>Colocando na equação: 0.003308 +/- (2.009575(0.0003117)). Que gera o intervalo (0.00268 e 0.00393). Um intervalo bem distante de 3, portanto pode-se rejeitar H0 pois os resultados foram estatísticamente significativos para isso.</p>
</div>
<div id="f-como-você-testaria-a-hipótese-de-normalidade-do-termo-de-erro-mostre-os-testes-que-usou." class="section level4">
<h4><strong>f) Como você testaria a hipótese de normalidade do termo de erro? Mostre os testes que usou.</strong></h4>
<p>Para testar a normalidade dos resíduos, pode-se usar o histograma e o qq-plot.</p>
<pre class="r"><code># Histograma dos resíduos
tbl_5.5 %&gt;%
  lm(formula = wage~expense) %&gt;% 
  residuals() %&gt;% data.frame(a = .) %&gt;%
  ggplot()+
  geom_histogram(mapping = aes(x = a), binwidth = .5, fill = graph_color, alpha = .5)+
  theme_graph()+
  labs(title = &quot;Residuals distribution&quot;,
       x = &quot;&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>tbl_5.5 %&gt;%
  lm(formula = wage~expense) %&gt;% 
  residuals() %&gt;% 
  data.frame(a = .) -&gt; res


# QQ plot
qqnorm(res$a, pch = 20)
qqline(res$a, pch = 1, col = &quot;dark orange&quot;, lty = 2)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
</div>
<div id="consulte-os-dados-da-tabela-3.20-e-monte-as-tabelas-anova-e-teste-a-hipótese-de-que-não-há-relação-entre-produtividade-e-salário-real.-faça-isso-para-o-setor-empresarial-e-para-o-setor-empresarial-não-agrícola." class="section level4">
<h4><strong>5.10) Consulte os dados da tabela 3.20 e monte as tabelas ANOVA e teste a hipótese de que não há relação entre produtividade e salário real. Faça isso para o setor empresarial e para o setor empresarial não agrícola.</strong></h4>
<pre class="r"><code>tbl_3.6 %&gt;% 
  head()</code></pre>
<pre><code>##    ano prod_setor_empresarial prod_setor_n_agricola sal_setor_empresarial
## 1 1960                   48.9                  51.9                  60.8
## 2 1961                   50.6                  53.5                  62.5
## 3 1962                   52.9                  55.9                  64.6
## 4 1963                   55.0                  57.8                  66.1
## 5 1964                   56.8                  59.6                  67.7
## 6 1965                   58.8                  61.4                  69.1
##   sal_setor_n_agricola
## 1                 63.3
## 2                 64.8
## 3                 66.7
## 4                 68.1
## 5                 69.3
## 6                 70.5</code></pre>
<pre class="r"><code>anova(tbl_3.6 %&gt;%
  lm(formula = prod_setor_empresarial~sal_setor_empresarial)) %&gt;% pander::pander()</code></pre>
<table style="width:100%;">
<caption>Analysis of Variance Table</caption>
<colgroup>
<col width="37%" />
<col width="6%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sal_setor_empresarial</strong></td>
<td align="center">1</td>
<td align="center">22610</td>
<td align="center">22610</td>
<td align="center">1830</td>
<td align="center">1.724e-37</td>
</tr>
<tr class="even">
<td align="center"><strong>Residuals</strong></td>
<td align="center">44</td>
<td align="center">543.6</td>
<td align="center">12.35</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
<pre class="r"><code>anova(tbl_3.6 %&gt;%
  lm(formula = prod_setor_n_agricola~sal_setor_n_agricola)) %&gt;% pander::pander()</code></pre>
<table>
<caption>Analysis of Variance Table</caption>
<colgroup>
<col width="36%" />
<col width="6%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sal_setor_n_agricola</strong></td>
<td align="center">1</td>
<td align="center">20478</td>
<td align="center">20478</td>
<td align="center">1874</td>
<td align="center">1.033e-37</td>
</tr>
<tr class="even">
<td align="center"><strong>Residuals</strong></td>
<td align="center">44</td>
<td align="center">480.7</td>
<td align="center">10.93</td>
<td align="center">NA</td>
<td align="center">NA</td>
</tr>
</tbody>
</table>
<p>A hipótese nula de que não há relação entre salário e produtividade pode ser rejeitada para os dois setors, visto que ambos geraram um valor f bastante pequeno.</p>
</div>
<div id="volte-ao-exercício-1.1-para-usar-os-dados-dele" class="section level4">
<h4><strong>5.12) Volte ao exercício 1.1 (para usar os dados dele)</strong></h4>
<pre class="r"><code># Amostra dos dados
tbl_1.3[sample(nrow(tbl_1.3),10), ]</code></pre>
<pre><code>##     Ano   EUA Canada Japão França Alemanha Italia Reino.Unido
## 14 1993 144.5  147.9 118.5  143.4    127.6  187.7       165.3
## 6  1985 107.6  109.0 104.2  114.3    104.8  121.7       111.1
## 11 1990 130.7  135.5 111.4  132.9    112.2  160.4       148.2
## 18 1997 160.5  156.3 121.5  153.2    137.8  218.2       185.1
## 25 2004 188.9  181.0 118.7  170.3    150.8  256.3       219.4
## 3  1982  96.5   94.9  98.1   91.7     97.0   87.8        95.4
## 19 1998 163.0  157.8 122.2  154.2    139.1  222.5       191.4
## 7  1986 109.6  113.5 104.9  117.2    104.6  128.9       114.9
## 2  1981  90.9   85.6  95.3   81.8     92.2   75.5        87.9
## 26 2005 195.3  184.9 118.3  173.2    153.7  261.3       225.6</code></pre>
</div>
<div id="a-trace-um-gráfico-com-os-dados-do-ipc-dos-estados-unidos-em-um-eixo-e-os-do-ipc-canandense-em-outro." class="section level4">
<h4><strong>a) Trace um gráfico com os dados do IPC dos Estados Unidos em um eixo e os do IPC canandense em outro.</strong></h4>
<pre class="r"><code>tbl_1.3 %&gt;%
  ggplot()+
  geom_point(mapping = aes(x = EUA, y = Canada), color = graph_color)+
  geom_abline(lty = 2, color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Canada and USA IPC correlation&quot;,
       x = &quot;EUA&quot;,
       y = &quot;Canada&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="b-suponha-que-você-queira-prever-o-ipc-dos-estados-unidos-com-base-no-ipc-do-canadá.-desenvolva-um-modelo-adequado." class="section level4">
<h4><strong>b) Suponha que você queira prever o IPC dos Estados Unidos com base no IPC do Canadá. Desenvolva um modelo adequado.</strong></h4>
<p>Com base no gráfico, pode-se desenvolver um modelo de regressão linear simples para fazer esta previsão. A regressão será:</p>
<p><span class="math inline">\(Ipc_u = \beta_0+\beta_1 \times Ipc_c\)</span></p>
<pre class="r"><code># Executando o modelo de regressão
tbl_1.3 %&gt;% 
  lm(formula = EUA~Canada) %&gt;% summary() %&gt;% pander::pander()</code></pre>
<table style="width:89%;">
<colgroup>
<col width="25%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">-8.542</td>
<td align="center">4.48</td>
<td align="center">-1.907</td>
<td align="center">0.06858</td>
</tr>
<tr class="even">
<td align="center"><strong>Canada</strong></td>
<td align="center">1.072</td>
<td align="center">0.03157</td>
<td align="center">33.96</td>
<td align="center">8.387e-22</td>
</tr>
</tbody>
</table>
<table style="width:88%;">
<caption>Fitting linear model: EUA ~ Canada</caption>
<colgroup>
<col width="20%" />
<col width="30%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Observations</th>
<th align="center">Residual Std. Error</th>
<th align="center"><span class="math inline">\(R^2\)</span></th>
<th align="center">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">26</td>
<td align="center">4.845</td>
<td align="center">0.9796</td>
<td align="center">0.9788</td>
</tr>
</tbody>
</table>
<p>Com base no output do R, obtém-se a seguinte regressão:</p>
<p><span class="math inline">\(\hat{Ipc_u} = -8.54164 + 1.07205 \times Ipc_c\)</span></p>
<p>Desta forma, com base na variação do IPC do Canadá, pode-se prever uma variação na mesma direção e de mesma magnitude nos Estados Unidos. O intercepto não é relevante no modelo, pois seu valor-p não é tão baixo. Sabendo que o valor-p mostra a probabilidade de se cometer um erro tipo I, é preferível não incluí-lo na equação. Portanto, ajustando a regressão acima, tem-se:</p>
<p><span class="math inline">\(\hat{Ipc_u} = 1.07205 \times Ipc_c\)</span></p>
<p>Com r² em 97.96% e uma estatística t para <span class="math inline">\(\beta_1\)</span> bastante alta (33.959), permitindo aceitá-la como estatísticamente significativa.</p>
</div>
<div id="c-teste-a-hipótese-de-que-não-há-relação-entre-os-ipcs-dos-dois-países.-use-um-nível-de-confiança-de-95.-se-h0-for-rejeitada-isso-significará-que-o-ipc-canadense-causa-o-ipc-dos-estados-unidos" class="section level4">
<h4><strong>c) Teste a hipótese de que não há relação entre os IPCs dos dois países. Use um nível de confiança de 95%. Se H0 for rejeitada, isso significará que o IPC canadense “causa” o IPC dos Estados Unidos?</strong></h4>
<p>Com base nos resultados acima, para testar a hipótese nula de que não há relação entre os IPCs dos dois países, basta analisar o valor-p ou a estatística t, ambos corroboram que há relação forte entre IPC canadense e americano. Portanto, pode-se rejeitar H0 pois os testes são estatisticamente significativos.</p>
<p>Porém isto não significa que o IPC canadense causa o IPC americano. O que ocorre é que ambos são afetados por outras variáveis econômicas que não estão representadas nos dados, por exemplo, taxa de juros, mercado acionário, ciclo econômico, demanda, confiança dos consumidores e empresas, taxa de desemprego, entre outras.</p>
</div>
<div id="volte-ao-exercício-3.22-para-fazer-uso-dos-dados." class="section level4">
<h4><strong>5.13) Volte ao exercício 3.22 para fazer uso dos dados.</strong></h4>
<pre class="r"><code># Amostra dos dados
tbl_3.7[sample(nrow(tbl_1.3),10), ]</code></pre>
<pre><code>##     ano gold_price nyse_index ipc_index
## 5  1978     193.22     567.81      65.2
## 11 1984     360.48     977.33     103.9
## 7  1980     612.56     720.15      82.4
## 8  1981     460.03     782.62      90.9
## 14 1987     446.46    1709.79     113.6
## 20 1993     359.77    2638.96     144.5
## 18 1991     362.11    2181.72     136.2
## 3  1976     124.84     575.85      56.9
## 24 1997     331.02    4827.35     160.5
## 12 1985     317.26    1142.97     107.6</code></pre>
</div>
<div id="a-estime-as-duas-regressões-dadas-neste-exercício-calculando-os-erros-padrão-e-os-demais-resultados-habituais." class="section level4">
<h4><strong>a) Estime as duas regressões dadas neste exercício, calculando os erros padrão e os demais resultados habituais.</strong></h4>
<p>As duas regressões se referem a (i) regressão IPC com o preço do ouro e (ii) IPC com o índice NYSE. Cada regressão buscando avaliar se a variável independente consegue proteger o investidor contra oscilações na inflação.</p>
<pre class="r"><code># Regressão do preço do ouro e inflação (IPC)
tbl_3.7 %&gt;%
  lm(formula = ipc_index~gold_price) %&gt;% summary() %&gt;% pander::pander()</code></pre>
<table style="width:88%;">
<colgroup>
<col width="25%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">68.47</td>
<td align="center">24.15</td>
<td align="center">2.835</td>
<td align="center">0.008003</td>
</tr>
<tr class="even">
<td align="center"><strong>gold_price</strong></td>
<td align="center">0.1693</td>
<td align="center">0.06624</td>
<td align="center">2.556</td>
<td align="center">0.0157</td>
</tr>
</tbody>
</table>
<table style="width:88%;">
<caption>Fitting linear model: ipc_index ~ gold_price</caption>
<colgroup>
<col width="20%" />
<col width="30%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Observations</th>
<th align="center">Residual Std. Error</th>
<th align="center"><span class="math inline">\(R^2\)</span></th>
<th align="center">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">33</td>
<td align="center">41.67</td>
<td align="center">0.1741</td>
<td align="center">0.1474</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Regressão do índice NYSE e inflação (IPC)
tbl_3.7 %&gt;%
  lm(formula = ipc_index~nyse_index) %&gt;% summary() %&gt;% pander::pander()</code></pre>
<table style="width:89%;">
<colgroup>
<col width="25%" />
<col width="15%" />
<col width="18%" />
<col width="13%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>(Intercept)</strong></td>
<td align="center">77.98</td>
<td align="center">5.037</td>
<td align="center">15.48</td>
<td align="center">3.897e-16</td>
</tr>
<tr class="even">
<td align="center"><strong>nyse_index</strong></td>
<td align="center">0.01668</td>
<td align="center">0.001313</td>
<td align="center">12.71</td>
<td align="center">7.895e-14</td>
</tr>
</tbody>
</table>
<table style="width:88%;">
<caption>Fitting linear model: ipc_index ~ nyse_index</caption>
<colgroup>
<col width="20%" />
<col width="30%" />
<col width="12%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Observations</th>
<th align="center">Residual Std. Error</th>
<th align="center"><span class="math inline">\(R^2\)</span></th>
<th align="center">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">33</td>
<td align="center">18.4</td>
<td align="center">0.8389</td>
<td align="center">0.8337</td>
</tr>
</tbody>
</table>
<p>O erro padrão para o ouro é de 0.06624 e para o índice NYSE é de 0.001313.</p>
</div>
<div id="b-teste-a-hipótese-de-que-os-termos-de-erro-dos-dois-modelos-de-regressão-distribuem-se-normalmente." class="section level4">
<h4><strong>b) Teste a hipótese de que os termos de erro dos dois modelos de regressão distribuem-se normalmente.</strong></h4>
<p>Primeiro é necessário extrair os resíduos e depois eles serão plotados em um histograma para validar a normalidade de sua distribuição.</p>
<pre class="r"><code># Resíduos da regressão 1
tbl_3.7 %&gt;%
  lm(formula = ipc_index~gold_price) %&gt;%
  residuals() %&gt;% data.frame(a = .) -&gt; res_1
  
res_1 %&gt;%
  ggplot()+
  geom_histogram(mapping = aes(x = a), fill = graph_color)+
  theme_graph()+
  labs(title = &quot;Regression model&#39;s residuals distribution&quot;,
       subtitle = &quot;IPC and gold price relation&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<pre class="r"><code># Resíduos da regressão 2
tbl_3.7 %&gt;%
  lm(formula = ipc_index~nyse_index) %&gt;%
  residuals() %&gt;% data.frame(a = .) -&gt; res_2
  
res_2 %&gt;%
  ggplot()+
  geom_histogram(mapping = aes(x = a), fill = graph_color)+
  theme_graph()+
  labs(title = &quot;Regression model&#39;s residuals distribution&quot;,
       subtitle = &quot;IPC and NYSE index relation&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
</div>
<div id="c-na-regressão-do-preço-do-ouro-teste-a-hipótese-de-que-beta-2-é-igual-a-1-ou-seja-de-que-há-uma-relação-de-um-para-um-entre-os-preços-do-ouro-e-o-ipc-o-ouro-é-um-hedge-perfeito.-qual-o-valor-p-da-estatística-t-estimada" class="section level4">
<h4><strong>c) Na regressão do preço do ouro, teste a hipótese de que beta 2 é igual a 1, ou seja, de que há uma relação de um para um entre os preços do ouro e o IPC (o ouro é um hedge perfeito). Qual o valor p da estatística t estimada?</strong></h4>
<p>Com base nos resultados da regressão estimada, <span class="math inline">\(\beta_2\)</span> ficou em 0.1693, com um erro padrçao de 0.06624, gerando uma estatística t de 2.556 e um valor p de 0.0157.</p>
<p>Para testar H0 com <span class="math inline">\(\beta_2 = 1\)</span> e H1 com <span class="math inline">\(\beta_2 \neq 1\)</span>, é preciso utilizar a fórmula:</p>
<p><span class="math inline">\(valor_t = \frac{|\hat{\beta_2} - \beta_2|}{SEM}\)</span></p>
<p><span class="math inline">\(valor_t = \frac{|0.1693 - 1|}{0.06624} = 12.54076\)</span></p>
<p>Este valor t de 12.54076 resulta em um valor p extremamente pequeno (pode ser validado abaixo)</p>
<pre class="r"><code># Valor p para um valor t de 12.54076
(1-pt(12.54076, 31))*2</code></pre>
<pre><code>## [1] 1.112443e-13</code></pre>
<p>Desta forma, pode-se rejeitar a hipótese nula de que <span class="math inline">\(\beta_2\)</span> é igual a 1 e consequentemente a ideia de que o ouro é um hedge perfeito contra inflação.</p>
</div>
<div id="d-repita-o-item-c-agora-com-a-regressão-do-índice-nyse.-o-investimento-no-mercado-de-ações-é-um-hedge-perfeito-contra-a-inflação-que-hipótese-nula-você-está-testando-qual-seu-valor-p" class="section level4">
<h4><strong>d) Repita o item (c), agora com a regressão do índice NYSE. O investimento no mercado de ações é um hedge perfeito contra a inflação? Que hipótese nula você está testando? Qual seu valor p?</strong></h4>
<p>Com base nos resultados da regressão, tem-se <span class="math inline">\(\beta_2 = 0.01668\)</span> com erro padrão em 0.001313, valor t de 12.71 e valor p bastante pequeno. Estes valores t e p são obtidos com base na hipótese nula de <span class="math inline">\(\beta_2 = 0\)</span>, desta forma, tem-se <span class="math inline">\(valor_t = \frac{\hat{\beta_2}}{SEM}\)</span> e o valor p obtido com auxílio do R e usando o valor t obtido.</p>
<p>Porém, no exercício pede-se para testar H0: <span class="math inline">\(\beta_2 = 1\)</span> e H1: <span class="math inline">\(\beta_2 \neq 1\)</span>. Com esta hipótese estabelecida, pode-se alterar a equação do valor t.</p>
<p><span class="math inline">\(valor_t = \frac{|\hat{\beta_2}-\beta_2|}{SEM}\)</span></p>
<p><span class="math inline">\(valor_t = \frac{|0.01668-1|}{0.001313} = 748.91\)</span></p>
<p>Este valor t é muito alto, obtiamente o valor p será extremamente pequeno. Desta forma pode-se rejeitar H0 com <span class="math inline">\(\beta_2 = 0\)</span> e consequentemente rejeitar a ideia de que o índice NYSE é um hedge perfeito contra inflação.</p>
</div>
<div id="e-entre-o-ouro-e-as-ações-qual-investimento-você-escolheria-em-que-se-baseia-sua-decisão" class="section level4">
<h4><strong>e) Entre o ouro e as ações, qual investimento você escolheria? Em que se baseia sua decisão?</strong></h4>
<p>Utilizando como parâmetro o investimento que mais irá proteger contra inflação, a melhor escolha é o investimento com variação mais próxima da variação do IPC, ou seja, <span class="math inline">\(\beta_2\)</span> mais próximo de 1 com baixo erro padrão. Desta forma, o ouro parece ser a melhor opção.</p>
</div>
<div id="a-tabela-5.6-apresenta-dados-sobre-pnb-e-quatro-definições-de-estoque-de-moeda-dos-estados-unidos-no-período-1970-1983.-fazendo-as-regressões-do-pnb-contra-as-várias-definições-de-moeda-obtemos-os-resultados-apresentados-na-tabela-5.7." class="section level4">
<h4><strong>5.14) A tabela 5.6 apresenta dados sobre PNB e quatro definições de estoque de moeda dos Estados Unidos no período 1970-1983. Fazendo as regressões do PNB contra as várias definições de moeda, obtemos os resultados apresentados na tabela 5.7.</strong></h4>
<pre class="r"><code>tbl_5.6 &lt;- read.table(file = paste(path,&quot;tabela_5.6_PNB_e_moedas.txt&quot;,sep = &quot;&quot;),
                      sep = &quot; &quot;,
                      header = T, 
                      dec = &quot;,&quot;)

# Amostra dos dados
tbl_5.6[sample(nrow(tbl_5.6),10), ]</code></pre>
<pre><code>##     ano    pnb    m1     m2     m3      l
## 6  1975 1549.2 291.2 1023.3 1174.2 1367.9
## 4  1973 1326.4 265.9  861.0  985.0 1141.7
## 3  1972 1185.9 252.0  805.2  886.0 1023.0
## 2  1971 1077.6 230.8  712.8  776.2  903.1
## 5  1974 1434.2 277.6  908.5 1070.5 1249.3
## 9  1978 2163.9 363.1 1389.1 1647.1 1910.6
## 1  1970  992.7 216.6  628.2  677.5  816.3
## 10 1979 2417.8 389.1 1498.5 1804.8 2117.1
## 8  1977 1918.3 335.4 1286.7 1472.9 1704.7
## 11 1980 2631.7 414.9 1632.6 1990.0 2326.2</code></pre>
</div>
<div id="a-que-definição-de-moeda-parece-apresentar-relação-mais-estreita-com-pnb-nominal" class="section level4">
<h4><strong>a) Que definição de moeda parece apresentar relação mais estreita com PNB nominal?</strong></h4>
<p>Para responder esta questão, basta verificar qual é a relação mais forte entre as 4 variáveis disponíveis.</p>
<pre class="r"><code>tbl_5.6 %&gt;% 
  tidyr::gather(&quot;campo&quot;,&quot;valor&quot;,3:6) %&gt;% 
  ggplot()+
  geom_point(mapping = aes(x = valor, y = pnb))+
  facet_wrap(~campo, scales = &quot;free&quot;)+
  scale_y_continuous(labels = scales::comma)+
  scale_x_continuous(labels = scales::comma)+
  theme_graph()+
  labs(title = &quot;PNB and Currency stock relation&quot;,
       x = &quot;Currency stock&quot;,
       y = &quot;PNB&quot;)</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>Aparentemente o estoquede moeda “M3” possui ligação mais forte com o valor do produto nacional bruto. Isso pode ser visto também pelo R² de cada variável, onde todas ficam acima de 99%, porém o maior valor é encontrado na relação entre PNB e Estoque de M3 (99.43%).</p>
</div>
</div>
</div>
<div id="section-5" class="section level2">
<h2><strong>6</strong></h2>
<div id="extensões-do-modelo-de-regressão-linear-de-duas-variáveis" class="section level3">
<h3><strong>Extensões do modelo de regressão linear de duas variáveis</strong></h3>
<div id="resumo-5" class="section level4">
<h4><strong>Resumo</strong></h4>
<p>Neste capítulo, os autores relembram a ideia de que o modelo de regressão linear deve ser linear nos parâmetros (<span class="math inline">\(\beta_1\)</span> e <span class="math inline">\(\beta_2\)</span>), porém não necessáriamente nas variáveis (X e Y). Desta forma, pode-se realizar manipulações em Y e X e gerar novos modelos que conseguem explicar melhor as relações entre variáveis.</p>
<p>O primeiro modelo tratado é o <strong>modelo que passa pela origem</strong>. Neste modelo, o intercepto não é utilizado e desta forma, tem-se o seguinte modelo:</p>
<p><span class="math display">\[Y_i = \beta_2 X_i + \mu_i\]</span>
A utilização deste modelo sem intercepto pode ser recomendada pela teoria por traz das variáveis estudadas, como por exemplo no modelo CAPM, há a construção do modelo:</p>
<p><span class="math display">\[ER - rf = \beta_i (ER_m - rf)\]</span>
Ao utilizar este modelo, os autores indicam que, diferentemente do modelo com intercepto, o valor de <span class="math inline">\(\sum{\mu_i}\)</span> pode ser diferente de zero. Também é indicado que a variável R² pode ser negativa, algo que não ocorre no modelo com intercepto. Este último fator faz com que muitos autores não apresentem o R² em modelos de regressão que passam pela origem.</p>
<p>Por fim, os autores recomendam que só seja utilizado este modelo caso haja fundamentação teórica que o recomende. Caso contrário, mantenha o modelo com uso do intercepto visto que caso esta variável não seja significativa, o resultado dos testes estatísticos irão indicar.</p>
<p>Dando sequência, os autores abordam o tema de <strong>escalas e unidades</strong> nos modelos de regressão. A ideia é identificar se mudanças de escalas irão afetar os resultados do modelo de regressão. Após alguns exemplos demonstrando esta possbilidade, tem-se a confirmação de que mudanças de escala não afetam no resultado final, apenas mudam a interpretação dos dados pelo leitor.</p>
<p>Após explicarem sobre escalas e unidades, os autores abordam a questão das variáveis padronizadas para o modelo de regressão. Variáveis padronizadas são o Y e o X do modelo, porém transformados da seguinte forma:</p>
<p><span class="math display">\[Y* = \frac{Y_j - \bar{Y}}{S_Y}\]</span></p>
<p><span class="math display">\[X* = \frac{X_j - \bar{X}}{S_X}\]</span></p>
<p>Esta padronização faz com que a média e o desvio padrão destas variáveis sejam 0 e 1 respectivamente. O uso de variáveis padronizadas no modelo de regressão é recomendado para modelos com mais de uma variável explicativa, pois os parâmetros <span class="math inline">\(\beta\)</span> serão comparados entre si para verificação de qual impacta mais no regressando Y. A interpretação será "se o regressor aumenta em 1 desvio padrão, o regressando padronizado aumenta em <span class="math inline">\(\beta\)</span> unidades de desvio padrão.
Após explicarem sobre variáveis padronizadas, os autores abordam o conceito de modelos logarítmicos do tipo log-log, lin-log e log-lin. Nesta etapa, há a explicação sobre o conceito de elasticidade (usada com modelos log-log) e taxa de crescimento (usada com modelos log-lin).</p>
<p>Por fim, é feita a explicação dos modelos recíprocos, que assumem a forma:</p>
<p><span class="math display">\[Y = \beta_1 + \beta_2 (\frac{1}{X}) + \mu\]</span></p>
<p>Estes modelos apresentam um valor assíntota para Y, ou seja, um valor que será assumido por Y caso X aumente indefinidamente. Este valor será de <span class="math inline">\(\beta_1\)</span>.</p>
<p>Ao final do capítulo, os autores indicam que a escolha do melhor modelo dependerá da teoria que está gerando as variáveis estudadas e do gráfico gerado por estas variáveis.</p>
</div>
<div id="exercícios-4" class="section level4">
<h4><strong>Exercícios</strong></h4>
</div>
<div id="com-base-na-tabela-6.7-ajuste-o-seguinte-modelo-aos-dados-e-obtenha-as-estatísticas-de-regressão-habituais.-interprete-os-resultados." class="section level4">
<h4><strong>6.14 Com base na tabela 6.7, ajuste o seguinte modelo aos dados e obtenha as estatísticas de regressão habituais. Interprete os resultados.</strong></h4>
<p><span class="math display">\[\frac{100}{100 - Y_i} = \beta_1 + \beta_2(\frac{1}{X_i})\]</span></p>
<pre class="r"><code>df &lt;- data.frame(y = c(86, 79, 76, 69, 65, 62, 52, 51, 51, 48),
                 x = c(3, 7, 12, 17, 25, 35, 45, 55, 70, 120))

df %&gt;% 
  ggplot()+
  geom_point(mapping = aes(x = x, y = y))</code></pre>
<p><img src="/library/2020-03-03-basic-econometrics-by-gujarati-and-porter_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<pre class="r"><code># Gerando o modelo de regressão recíproco
lm &lt;- df %&gt;% 
  lm(formula = &quot;100/(100-y) ~ I(1/x)&quot;) %&gt;% summary() %&gt;% pander::pander()</code></pre>
<p>Com base nos resultados, pode-se concluir que Y tenderá ao valor de 51.64 com base em valores cada vez maiores de X. Ou seja, 51.64 é o valor assintótico de Y no modelo.</p>
</div>
</div>
</div>
<div id="section-6" class="section level2">
<h2><strong>7</strong></h2>
<div id="análise-de-regressão-múltipla-o-problema-da-estimação" class="section level3">
<h3><strong>Análise de regressão múltipla: O problema da estimação</strong></h3>
<div id="resumo-6" class="section level4">
<h4><strong>Resumo</strong></h4>
</div>
</div>
</div>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

