\documentclass[12pt, letterpaper]{article}

% Preamble
\title{Monte Carlo Simulations Applied on Discounted Cash Flow}
\author{Francisco Piccolo}
\date{}

\begin{document}

\maketitle

\tableofcontents

\begin{abstract}

This is a simple abstract

\end{abstract}

\section{Introduction}

\section{Methodology}

\subsection{Monte Carlo Simulation}

\subsection{Discounted Cash Flow}

\section{Results}

\end{document}