<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="Francisco Piccolo ">
<meta name="description" content="The linear regression model is highly used on the prediction of continuous variables, where is one or more independent variables and one dependent one (the one that it seeks to test an hypothesis about its behavior). This is a pretty simple model to by executed and one of the firsts to be taught in econometric classes. Although its simplicity, in order to reach reliable results, some assumptions are needed, like the following:" />
<meta name="keywords" content="" />
<meta name="robots" content="noodp" />
<meta name="theme-color" content="#252627" />
<link rel="canonical" href="/posts/2019/09/residual-analysis-in-econometric-models/" />


    <title>
        
            Residual analysis in econometric models :: Glass Frog  — Hello Friend NG Theme
        
    </title>



<link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/css/flag-icon.min.css" rel="stylesheet"
    type="text/css">



<link rel="stylesheet" href="/main.min.753fac8f03736f0edc9be411eb20cee875dd7bb8e73c8155fbf6a629c863f4ca.css">




    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#252627">
    <link rel="shortcut icon" href="/favicon.ico">
    <meta name="msapplication-TileColor" content="#252627">
    <meta name="theme-color" content="#252627">



<meta itemprop="name" content="Residual analysis in econometric models">
<meta itemprop="description" content="The linear regression model is highly used on the prediction of continuous variables, where is one or more independent variables and one dependent one (the one that it seeks to test an hypothesis about its behavior). This is a pretty simple model to by executed and one of the firsts to be taught in econometric classes. Although its simplicity, in order to reach reliable results, some assumptions are needed, like the following:">
<meta itemprop="datePublished" content="2019-09-05T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2019-09-05T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="1264">
<meta itemprop="image" content="/"/>



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="/"/>

<meta name="twitter:title" content="Residual analysis in econometric models"/>
<meta name="twitter:description" content="The linear regression model is highly used on the prediction of continuous variables, where is one or more independent variables and one dependent one (the one that it seeks to test an hypothesis about its behavior). This is a pretty simple model to by executed and one of the firsts to be taught in econometric classes. Although its simplicity, in order to reach reliable results, some assumptions are needed, like the following:"/>







    <meta property="article:published_time" content="2019-09-05 00:00:00 &#43;0000 UTC" />








    </head>

    <body class="dark-theme">
        <div class="container">
            <header class="header">
    <span class="header__inner">
        <a href="/" style="text-decoration: none;">
    <div class="logo">
        
            <span class="logo__mark">></span>
            <span class="logo__text">Home</span>
            <span class="logo__cursor" style=
                  "
                   
                   ">
            </span>
        
    </div>
</a>


        <span class="header__right">
            
                <nav class="menu">
    <ul class="menu__inner"><li><a href="/about/">About</a></li><li><a href="/books/">Book Review</a></li><li><a href="/posts/">Posts</a></li>
    </ul>
</nav>

                <span class="menu-trigger">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path d="M0 0h24v24H0z" fill="none"/>
                        <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/>
                    </svg>
                </span>
            

            <span class="theme-toggle unselectable"><svg class="theme-toggler" width="24" height="24" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M22 41C32.4934 41 41 32.4934 41 22C41 11.5066 32.4934 3 22
  3C11.5066 3 3 11.5066 3 22C3 32.4934 11.5066 41 22 41ZM7 22C7
  13.7157 13.7157 7 22 7V37C13.7157 37 7 30.2843 7 22Z"/>
</svg>
</span>
        </span>
    </span>
</header>


            <div class="content">
                
    <main class="post">

        <div class="post-info">
            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>6 minutes

            

            </p>
        </div>

        <article>
            <h1 class="post-title">
                <a href="/posts/2019/09/residual-analysis-in-econometric-models/">Residual analysis in econometric models</a>
            </h1>

            

            <div class="post-content">
                


<p>The linear regression model is highly used on the prediction of continuous variables, where is one or more independent variables and one dependent one (the one that it seeks to test an hypothesis about its behavior). This is a pretty simple model to by executed and one of the firsts to be taught in econometric classes. Although its simplicity, in order to reach reliable results, some assumptions are needed, like the following:</p>
<ol style="list-style-type: lower-roman">
<li><p>Absence of multicolineatiry between independent variables.</p></li>
<li><p>Absence of autocorrelation on the dependent variable.</p></li>
<li><p>Absence of pattern on the behavior of the model residuals, in other words, absence of heteroscedasticity.</p></li>
<li><p>Normal distribution of residuals.</p></li>
</ol>
<p>Having this assumptions satisfied, the model can be executed and the generated conclusions will be reliable to allow decision making. In this post, I’ll analyse the behavior of the residuals for a linear regression model in order to validate the assumptions (iii) and (iv). For this, I’ll use a data set that presents the price of suggarcane as independent variable and the planted area of this product, that will be the dependent variable.</p>
<p>The goal of this example is to analyse, through a simple linear regression model, the suggarcane supply elasticity as a function of the suggarcane price. The hipothesis is that there’s elasticity on the supply, thus the planted area increases in responde to a price increase. But, in order to validade this existence, it’s necessary to check, using a regression model, that these two variables have correlation. Then, the assumptions (iii) and (iv) will support this conclusion.</p>
<p>For this example, I’ll utilize the following R packages:</p>
<pre class="r"><code>library(tidyverse)
library(lmtest)
library(corrplot)
library(readxl)

theme_graph &lt;- function(){
  theme(
    plot.title = element_text(size = 16),
    plot.subtitle = element_text(size = 12),
    plot.caption = element_text(face = &quot;italic&quot;, size = 9),
    axis.text = element_text(size = 9),
    axis.title = element_text(face = &quot;italic&quot;, size = 9),
    strip.background = element_rect(fill = &quot;grey&quot;),
    strip.text = element_text(face = &quot;bold&quot;),
    legend.title = element_blank(),
    legend.position = &quot;bottom&quot;
  )
}
  
graph_color &lt;- &quot;#006666&quot;</code></pre>
<p>The data set for this example has 34 rows, with planted area and suggarcane price fields.</p>
<pre class="r"><code># Getting the dataset
dados &lt;- readxl::read_excel(&quot;C:/Users/francisco.piccolo/Desktop/R/franciscopiccolo.github.io/datasets/Econometria_exercicios/autocorrelacao_cana_de_acucar.xlsx&quot;)

# Chaging the name of the fields to remove blank spaces
dados %&gt;% 
  transmute(period = Período,
            area = Área,
            price = `Preço da Cana de Açúcar`*100) -&gt; df</code></pre>
<p>Lets see a sample of this dataset.</p>
<pre class="r"><code>df[sample(nrow(df),5), ] %&gt;%
    as.tibble()</code></pre>
<pre><code>## # A tibble: 5 x 3
##   period  area price
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     28   152  40.5
## 2     13   125  19.4
## 3     27    97  40.1
## 4     34   235  39.2
## 5     12    80  14.6</code></pre>
<p>The linear regression model proposed for this problem is defined by the following equation:</p>
<p><span class="math display">\[ lnY_t = \beta_0+\beta_1 (lnX_t) + \mu_t \]</span></p>
<p>Where:</p>
<p><span class="math inline">\(Y_t\)</span> = planted area, natural log transformed</p>
<p><span class="math inline">\(X_t\)</span> = suggarcane price, natural log transformed</p>
<p><span class="math inline">\(\beta_0\)</span> = intercept</p>
<p><span class="math inline">\(\beta_1\)</span> = slope</p>
<p><span class="math inline">\(\mu_t\)</span> = residuals</p>
<p>The natural log is used to in order to have variations between periods interpreted as percentual variation. This assumption is made possible only for natural log transformations and this adjustment is needed in problems invonving elasticity, because elasticity is interpreted as a percentual variation in one variable given a percentual variation in another variable.</p>
<p>The following graph shows the behavior of the studied variables and the regression line.</p>
<pre class="r"><code>df %&gt;% 
  ggplot()+
  geom_point(mapping = aes(x = price, y = area), shape = 20)+
  geom_smooth(mapping = aes(x = price, y = area), 
              method = &quot;lm&quot;, 
              formula = y ~ x, 
              se = F, 
              lty = 2,
              color = &quot;dark orange&quot;)+
  theme_graph()+
  labs(title = &quot;Dispersion graph for the model&quot;)</code></pre>
<p><img src="/posts/2019-09-05-residual-analysis-in-econometric-models_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>In order to develop the model using the log transformation, there’re two options:</p>
<ol style="list-style-type: lower-roman">
<li><p>Adjust the variables on the dataset and build the normal using the new variables generated by the log scale calculation.</p></li>
<li><p>Use the original dataset and inform adjust the model to apply the transformation on the variables before calculating the parameters.</p></li>
</ol>
<p>Lets see each one of theses methods to confirm they’re equal:</p>
<p><strong>(i) </strong></p>
<pre class="r"><code>df %&gt;% 
  mutate(area_log = log(area),
         price_log = log(price)) %&gt;% 
  lm(formula = area_log ~ price_log) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = area_log ~ price_log, data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.65076 -0.18823 -0.03096  0.24914  0.60492 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.6416     0.3534   4.645 5.56e-05 ***
## price_log     0.9706     0.1106   8.773 5.03e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3088 on 32 degrees of freedom
## Multiple R-squared:  0.7063, Adjusted R-squared:  0.6972 
## F-statistic: 76.97 on 1 and 32 DF,  p-value: 5.031e-10</code></pre>
<p><strong>(ii)</strong></p>
<pre class="r"><code>df %&gt;% 
  lm(formula = log(area) ~ log(price)) %&gt;% 
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(area) ~ log(price), data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.65076 -0.18823 -0.03096  0.24914  0.60492 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.6416     0.3534   4.645 5.56e-05 ***
## log(price)    0.9706     0.1106   8.773 5.03e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3088 on 32 degrees of freedom
## Multiple R-squared:  0.7063, Adjusted R-squared:  0.6972 
## F-statistic: 76.97 on 1 and 32 DF,  p-value: 5.031e-10</code></pre>
<p>As indicated, the two alternatives generate the same result. It’s up to the researcher to choose the method. The regression model generated is:</p>
<p><span class="math display">\[\hat{Y} = 1.6416 + 0.9706X_1 + \mu\]</span>
With both intercept and slope statistically significant given their low p-value.</p>
<p>The r² reach 70.6%, but this isn’t enough to make conclusions about the model. Its necessary to analyse the model hypothesis about the residuals to ensure that the model is reliable. The following code return the residuals from a ‘lm’ model.</p>
<pre class="r"><code>model_residuals &lt;- 
  data.frame(values = df %&gt;% 
                        lm(formula = log(area) ~ log(price)) %&gt;% 
                        residuals())</code></pre>
<p>The next graph shows the residuals distribution in order to validate if they’re normally distributed. Both histogram and quantil-quantil plot are good choices to validate this assumption.</p>
<pre class="r"><code># Histogram
model_residuals %&gt;% 
  ggplot()+
  geom_histogram(mapping = aes(x = values), fill = &quot;dark orange&quot;, alpha = .5)+
  theme_graph()+
  labs(title = &quot;Residuals Distribution&quot;,
       x = &quot;&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/posts/2019-09-05-residual-analysis-in-econometric-models_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code># q-q plot
model_residuals %&gt;% 
  ggplot()+
  geom_qq(mapping = aes(sample = values))+
  theme_graph()+
  labs(title = &quot;Residuals&#39; Q-Q plot&quot;,
       x = &quot;&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/posts/2019-09-05-residual-analysis-in-econometric-models_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Both graphs enforce the ideia that the model’s residuals are normally distributed. But in order to make a conclusion, sometimes a formal test will be necessary. For this problem, we’ll use the Durbin Watson test. This test can be performed using the following code.</p>
<pre class="r"><code>lmtest::dwtest(df %&gt;% 
                 lm(formula = log(area) ~ log(price)))</code></pre>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  df %&gt;% lm(formula = log(area) ~ log(price))
## DW = 1.2912, p-value = 0.009801
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>The test generate the value of 1.2912, but only this value isn’t enough to make the conclusion. As well as the DW value, DL and DU intervals are necessary. These values can be found at this <a href="http://www.portalaction.com.br/analise-de-regressao/33-diagnostico-de-independencia">table</a>. In order to find them, take the number of observations of the dataset (n = 33), the significance level of your test (i.e. 0.05) and the degress of freedom (i.e. 1). Thus we have:</p>
<p><strong>DL</strong> = 1.35</p>
<p><strong>DU</strong> = 1.49</p>
<p>With a DW of 1.2912, above 0 and under the DL value, we can conclude that the residuals are independent.</p>
<p>To conclude, both graphs and formal tests confirmed that the residuals are independent and then we have the hypothesis of the model satisfied, allowing inferences about the problem being studies, in this case, the elasticity of the suggarcane supply given it’s price variability.</p>

            </div>
        </article>

        <hr />

        <div class="post-info">

            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>1264 Words</p>

            <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>2019-09-04 21:00 -0300</p>
        </div>

        
    </main>

            </div>

            
                <footer class="footer">
    <div class="footer__inner">
        <div class="footer__content">
            <span>&copy; 2020</span>
            
                <span><a href="/">Francisco Piccolo</a></span>
            
            <span></span>
            <span> <a href="/posts/index.xml" target="_blank" title="rss"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"><path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle></svg></a></span>
        </div>
    </div>
    <div class="footer__inner">
        <div class="footer__content">
            <span>Powered by <a href="http://gohugo.io">Hugo</a></span>
            <span>Made with &#10084; by <a href="https://github.com/rhazdon">Djordje Atlialp</a></span>
        </div>
    </div>
    
    
    
        <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
        
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                processEscapes: true,
                processEnvironments: true
            },
            // Center justify equations in code and markdown cells. Elsewhere
            // we use CSS to left justify single line equations in code cells.
            displayAlign: 'center',
            "HTML-CSS": {
                styles: {'.MathJax_Display': {"margin": 0}},
                linebreaks: { automatic: true }
            }
        });
        </script>
        

</footer>

            
        </div>

        




<script type="text/javascript" src="/bundle.min.4a69500057d68129e88f497d354afe68422eb56de6d15e45dbe2190858ea5a76bfcb096406f992984b241db45f47388ac57ab0376e3b32125bef7a8a6d0f06c4.js" integrity="sha512-SmlQAFfWgSnoj0l9NUr&#43;aEIutW3m0V5F2&#43;IZCFjqWna/ywlkBvmSmEskHbRfRziKxXqwN247MhJb73qKbQ8GxA=="></script>



    </body>
</html>
